var breakfast = [
  {
    n: "Overnight Oats Banane Amandes",
    f: "🇺🇸",
    k: 422,
    p: 18,
    g: 56,
    l: 14,
    lv: 1,
    i: "Flocons d'avoine 80g, lait écrémé 200ml, banane 100g, amandes effilées 20g, miel 10g",
    st: ["Mélanger les flocons d'avoine avec le lait dans un bol.", "Ajouter le miel et remuer.", "Réfrigérer une nuit. Garnir de banane tranchée et d'amandes avant de servir."],
    w: false,
    tags: ["avoine", "banane", "amandes", "miel", "lait"]
  },
  {
    n: "Avocado Toast Oeuf Poché",
    f: "🇦🇺",
    k: 458,
    p: 20,
    g: 36,
    l: 26,
    lv: 2,
    i: "Pain complet 80g, avocat 100g, oeuf 60g, citron 10ml, piment rouge 2g, sel, poivre",
    st: ["Faire pocher l'oeuf dans de l'eau frémissante avec un peu de vinaigre.", "Écraser l'avocat avec le citron, sel et piment.", "Tartiner le pain grillé d'avocat et poser l'oeuf par-dessus."],
    w: false,
    tags: ["pain", "avocat", "oeuf", "citron"]
  },
  {
    n: "Yaourt Grec Myrtilles Granola",
    f: "🇬🇷",
    k: 386,
    p: 26,
    g: 48,
    l: 10,
    lv: 1,
    i: "Yaourt grec 0% 200g, myrtilles 100g, granola 60g, miel 10g",
    st: ["Verser le yaourt dans un bol.", "Ajouter les myrtilles fraîches et le granola.", "Drizzler de miel et servir immédiatement."],
    w: false,
    tags: ["yaourt", "myrtilles", "granola", "miel"]
  },
  {
    n: "Porridge Pomme Cannelle",
    f: "🇬🇧",
    k: 384,
    p: 14,
    g: 64,
    l: 8,
    lv: 1,
    i: "Flocons d'avoine 90g, lait demi-écrémé 250ml, pomme 120g, cannelle 2g, miel 15g",
    st: ["Porter le lait à ébullition, ajouter les flocons d'avoine.", "Cuire 5 min à feu doux en remuant.", "Servir avec la pomme râpée, la cannelle et le miel."],
    w: false,
    tags: ["avoine", "pomme", "cannelle", "miel", "lait"]
  },
  {
    n: "Oeufs Brouillés Pain Seigle",
    f: "🇩🇪",
    k: 446,
    p: 28,
    g: 34,
    l: 22,
    lv: 2,
    i: "Oeufs 3x60g, pain de seigle 80g, beurre 15g, ciboulette 5g, sel, poivre",
    st: ["Battre les oeufs avec sel et poivre.", "Faire fondre le beurre à feu doux, verser les oeufs.", "Remuer doucement jusqu'à texture crémeuse. Servir sur pain de seigle grillé avec ciboulette."],
    w: false,
    tags: ["oeuf", "pain", "seigle", "beurre", "ciboulette"]
  },
  {
    n: "Shakshuka Tomate Poivron",
    f: "🇮🇱",
    k: 376,
    p: 22,
    g: 18,
    l: 24,
    lv: 2,
    i: "Oeufs 3x60g, tomates pelées 200g, poivron rouge 100g, oignon 60g, huile d'olive 20ml, cumin 2g, paprika 2g",
    st: ["Faire revenir l'oignon et le poivron dans l'huile d'olive.", "Ajouter les tomates, cumin, paprika, mijoter 10 min.", "Creuser des puits, casser les oeufs dedans, couvrir et cuire 5 min."],
    w: false,
    tags: ["oeuf", "tomate", "poivron", "oignon", "huile"]
  },
  {
    n: "Smoothie Bowl Açaí",
    f: "🇧🇷",
    k: 418,
    p: 14,
    g: 68,
    l: 10,
    lv: 1,
    i: "Pulpe d'açaí 100g, banane 100g, lait de coco 80ml, granola 50g, fraises 80g, miel 10g",
    st: ["Mixer la pulpe d'açaí avec la banane et le lait de coco.", "Verser dans un bol.", "Garnir de granola, fraises et miel."],
    w: false,
    tags: ["açaí", "banane", "granola", "fraises", "lait de coco"]
  },
  {
    n: "Bol Riz Tamago Japonais",
    f: "🇯🇵",
    k: 430,
    p: 18,
    g: 58,
    l: 14,
    lv: 2,
    i: "Riz japonais 120g (cuit 240g), oeuf 2x60g, sauce soja 15ml, huile de sésame 8ml, nori 5g, sésame 5g",
    st: ["Cuire le riz japonais.", "Battre les oeufs avec la sauce soja.", "Verser les oeufs crus sur le riz chaud, mélanger vivement. Finir avec huile de sésame et nori."],
    w: false,
    tags: ["riz", "oeuf", "soja", "sésame", "nori"]
  },
  {
    n: "Pancakes Banane Avoine",
    f: "🇺🇸",
    k: 468,
    p: 30,
    g: 60,
    l: 12,
    lv: 2,
    i: "Flocons d'avoine 100g, banane 100g, oeufs 2x60g, lait écrémé 100ml, levure 3g",
    st: ["Mixer tous les ingrédients en pâte lisse.", "Cuire des petites crêpes épaisses dans une poêle antiadhésive.", "Servir avec un filet de miel ou sirop d'érable."],
    w: false,
    tags: ["avoine", "banane", "oeuf", "lait"]
  },
  {
    n: "Galette Sarrasin Oeuf Épinards",
    f: "🇫🇷",
    k: 392,
    p: 22,
    g: 40,
    l: 16,
    lv: 2,
    i: "Farine de sarrasin 80g, oeuf 60g, épinards frais 80g, emmental râpé 30g, beurre 10g, eau 150ml",
    st: ["Préparer la pâte avec farine de sarrasin, eau et oeuf. Laisser reposer 30 min.", "Cuire une galette fine dans une crêpière beurrée.", "Garnir d'épinards sautés et d'emmental, replier les bords."],
    w: false,
    tags: ["sarrasin", "oeuf", "épinards", "fromage"]
  },
  {
    n: "French Toast Cannelle Banane",
    f: "🇫🇷",
    k: 454,
    p: 26,
    g: 56,
    l: 14,
    lv: 2,
    i: "Pain de mie complet 100g, oeufs 2x60g, lait écrémé 100ml, banane 100g, cannelle 2g, vanille 2ml",
    st: ["Battre les oeufs avec le lait, la cannelle et la vanille.", "Tremper les tranches de pain dans le mélange.", "Cuire 2-3 min de chaque côté dans une poêle légèrement huilée. Servir avec banane tranchée."],
    w: false,
    tags: ["pain", "oeuf", "lait", "banane", "cannelle"]
  },
  {
    n: "Müesli Bircher Pomme",
    f: "🇨🇭",
    k: 454,
    p: 20,
    g: 62,
    l: 14,
    lv: 1,
    i: "Flocons d'avoine 80g, yaourt nature 150g, pomme 120g, noisettes 20g, raisins secs 20g, jus de citron 10ml",
    st: ["Mélanger les flocons d'avoine avec le yaourt et le jus de citron.", "Ajouter la pomme râpée, les raisins secs et les noisettes.", "Réfrigérer toute la nuit et servir frais."],
    w: false,
    tags: ["avoine", "yaourt", "pomme", "noisettes", "raisins"]
  },
  {
    n: "Toast Saumon Fumé Aneth",
    f: "🇸🇪",
    k: 420,
    p: 28,
    g: 32,
    l: 20,
    lv: 1,
    i: "Pain complet 80g, saumon fumé 100g, fromage frais 60g, aneth 5g, câpres 10g, citron 10ml",
    st: ["Griller le pain.", "Tartiner de fromage frais.", "Disposer le saumon fumé, les câpres, l'aneth et un filet de citron."],
    w: false,
    tags: ["pain", "saumon", "fromage frais", "aneth", "câpres"]
  },
  {
    n: "Congee Poulet Gingembre",
    f: "🇨🇳",
    k: 384,
    p: 32,
    g: 46,
    l: 8,
    lv: 2,
    i: "Riz rond 80g, blancs de poulet 120g, gingembre 10g, bouillon de volaille 600ml, oignons verts 20g, sauce soja 10ml",
    st: ["Porter le bouillon à ébullition avec le riz et le gingembre.", "Cuire 30-40 min à feu doux jusqu'à texture crémeuse.", "Ajouter le poulet effiloché, finir avec oignons verts et sauce soja."],
    w: false,
    tags: ["riz", "poulet", "gingembre", "oignon vert", "soja"]
  },
  {
    n: "Tamagoyaki Omelette Roulée",
    f: "🇯🇵",
    k: 352,
    p: 24,
    g: 10,
    l: 24,
    lv: 3,
    i: "Oeufs 4x60g, sauce soja 10ml, mirin halal 10ml, sucre 5g, huile 10ml, oignons verts 15g",
    st: ["Battre les oeufs avec la sauce soja, mirin et sucre.", "Chauffer une poêle rectangulaire, huiler légèrement.", "Verser un tiers de la pâte, rouler délicatement à l'aide d'une spatule. Répéter 3 fois pour former un rouleau compact."],
    w: false,
    tags: ["oeuf", "soja", "oignon vert"]
  },
  {
    n: "Eggs Benedict Saumon",
    f: "🇺🇸",
    k: 480,
    p: 32,
    g: 34,
    l: 24,
    lv: 3,
    i: "Muffin anglais 70g, saumon fumé 80g, oeuf 2x60g, sauce hollandaise 40g (sans beurre d'alcool), épinards 40g",
    st: ["Griller les muffins anglais.", "Pocher les oeufs dans de l'eau frémissante.", "Assembler: muffin, épinards, saumon, oeuf poché, sauce hollandaise."],
    w: false,
    tags: ["muffin", "saumon", "oeuf", "sauce hollandaise", "épinards"]
  },
  {
    n: "Fluffy Pancakes Soufflés",
    f: "🇯🇵",
    k: 438,
    p: 22,
    g: 56,
    l: 14,
    lv: 3,
    i: "Farine 90g, oeufs 2x60g, lait 100ml, yaourt 80g, levure 5g, sucre 15g, beurre 10g",
    st: ["Séparer les blancs des jaunes d'oeufs. Monter les blancs en neige ferme.", "Mélanger les jaunes, farine, lait, yaourt, sucre et levure.", "Incorporer délicatement les blancs en neige. Cuire à feu très doux 4 min par côté sous couvercle."],
    w: false,
    tags: ["farine", "oeuf", "lait", "yaourt", "beurre"]
  },
  {
    n: "Crêpes Sarrasin Miel Noix",
    f: "🇫🇷",
    k: 412,
    p: 24,
    g: 52,
    l: 12,
    lv: 2,
    i: "Farine de sarrasin 80g, oeuf 60g, lait écrémé 200ml, noix concassées 20g, miel 15g, beurre 8g",
    st: ["Préparer la pâte de sarrasin avec oeuf, farine et lait.", "Cuire des crêpes fines dans une poêle beurrée.", "Servir avec miel et noix concassées."],
    w: false,
    tags: ["sarrasin", "oeuf", "lait", "noix", "miel"]
  },
  {
    n: "Bol Açaí Fraises Granola",
    f: "🇧🇷",
    k: 394,
    p: 20,
    g: 38,
    l: 18,
    lv: 1,
    i: "Pulpe d'açaí 100g, fraises 100g, granola 50g, yaourt grec 100g, graines de chia 10g",
    st: ["Mixer l'açaí avec les fraises.", "Verser dans un bol, déposer le yaourt grec par-dessus.", "Garnir de granola et graines de chia."],
    w: false,
    tags: ["açaí", "fraises", "granola", "yaourt", "chia"]
  },
  {
    n: "Toast Avocat Oeuf Dur Tomate",
    f: "🇦🇺",
    k: 374,
    p: 18,
    g: 44,
    l: 14,
    lv: 1,
    i: "Pain complet 80g, avocat 60g, oeuf dur 60g, tomate 80g, jus de citron 5ml, sel, poivre",
    st: ["Griller le pain complet.", "Écraser l'avocat avec citron, sel et poivre.", "Disposer l'avocat sur le pain, garnir d'oeuf dur tranché et de tomate."],
    w: false,
    tags: ["pain", "avocat", "oeuf", "tomate"]
  },
  {
    n: "Porridge Banane Chocolat Noir",
    f: "🇬🇧",
    k: 394,
    p: 16,
    g: 60,
    l: 10,
    lv: 1,
    i: "Flocons d'avoine 90g, lait écrémé 250ml, banane 100g, pépites de chocolat noir 15g, miel 10g",
    st: ["Cuire les flocons d'avoine dans le lait à feu doux 5 min.", "Trancher la banane et disposer sur le porridge.", "Parsemer de pépites de chocolat et drizzler de miel."],
    w: false,
    tags: ["avoine", "lait", "banane", "chocolat", "miel"]
  },
  {
    n: "Omelette Épinards Feta Tomate",
    f: "🇬🇷",
    k: 408,
    p: 28,
    g: 20,
    l: 24,
    lv: 2,
    i: "Oeufs 3x60g, épinards frais 80g, feta 40g, tomate 80g, huile d'olive 10ml, origan 2g",
    st: ["Battre les oeufs avec sel et origan.", "Faire revenir les épinards et la tomate dans l'huile d'olive.", "Verser les oeufs, cuire 3 min, ajouter la feta émiettée et plier."],
    w: false,
    tags: ["oeuf", "épinards", "feta", "tomate", "huile"]
  },
  {
    n: "Bowl Quinoa Fruits Rouges Miel",
    f: "🇺🇸",
    k: 410,
    p: 26,
    g: 36,
    l: 18,
    lv: 1,
    i: "Quinoa 80g (cuit 160g), yaourt grec 150g, framboises 80g, myrtilles 60g, amandes 20g, miel 10g",
    st: ["Cuire le quinoa, laisser refroidir.", "Assembler dans un bol: quinoa, yaourt grec, fruits rouges.", "Garnir d'amandes et de miel."],
    w: false,
    tags: ["quinoa", "yaourt", "framboises", "myrtilles", "amandes"]
  },
  {
    n: "Crumpets Oeuf Fromage Blanc",
    f: "🇬🇧",
    k: 384,
    p: 30,
    g: 30,
    l: 16,
    lv: 2,
    i: "Crumpets 2x50g, oeufs 2x60g, fromage blanc 0% 120g, ciboulette 5g, saumon fumé 50g",
    st: ["Griller les crumpets.", "Poêler les oeufs au plat.", "Servir les crumpets garnis de fromage blanc, oeuf et saumon, parsemer de ciboulette."],
    w: false,
    tags: ["crumpet", "oeuf", "fromage blanc", "saumon", "ciboulette"]
  },
  {
    n: "Muesli Noix Fruits Secs Yaourt",
    f: "🇨🇭",
    k: 380,
    p: 22,
    g: 46,
    l: 12,
    lv: 1,
    i: "Flocons d'avoine 70g, yaourt nature 200g, noix 20g, abricots secs 30g, graines de lin 10g, miel 10g",
    st: ["Tremper les flocons d'avoine dans le yaourt une nuit.", "Ajouter noix concassées, abricots secs et graines de lin.", "Finir avec un filet de miel."],
    w: false,
    tags: ["avoine", "yaourt", "noix", "abricot", "lin", "miel"]
  },
  {
    n: "Wrap Petit Déjeuner Oeuf Avocat",
    f: "🇲🇽",
    k: 388,
    p: 20,
    g: 50,
    l: 12,
    lv: 2,
    i: "Tortilla de blé 60g, oeuf brouillé 2x60g, avocat 60g, tomate 60g, poivron 40g, épices 2g",
    st: ["Brouiller les oeufs avec sel et épices.", "Chauffer la tortilla.", "Garnir d'oeufs brouillés, avocat, tomate et poivron. Rouler."],
    w: false,
    tags: ["tortilla", "oeuf", "avocat", "tomate", "poivron"]
  },
  {
    n: "Gaufres Avoine Miel Myrtilles",
    f: "🇧🇪",
    k: 386,
    p: 12,
    g: 62,
    l: 10,
    lv: 2,
    i: "Flocons d'avoine 100g, lait écrémé 150ml, oeuf 60g, miel 20g, myrtilles 100g, huile 5ml",
    st: ["Mixer les flocons d'avoine en poudre fine. Mélanger avec lait, oeuf et miel.", "Cuire dans un gaufrier huilé.", "Servir avec les myrtilles fraîches."],
    w: false,
    tags: ["avoine", "lait", "oeuf", "miel", "myrtilles"]
  },
  {
    n: "Burritos Petit Déjeuner Haricots",
    f: "🇲🇽",
    k: 392,
    p: 24,
    g: 38,
    l: 16,
    lv: 2,
    i: "Tortilla 70g, haricots noirs 100g, oeuf 2x60g, fromage râpé 30g, salsa 40g, épinards 40g",
    st: ["Brouiller les oeufs.", "Chauffer les haricots noirs à la poêle.", "Assembler la tortilla avec oeufs, haricots, fromage et salsa. Rouler."],
    w: false,
    tags: ["tortilla", "haricots", "oeuf", "fromage", "salsa", "épinards"]
  },
  {
    n: "Bowl Fromage Blanc Fruits Graines",
    f: "🇫🇷",
    k: 394,
    p: 26,
    g: 32,
    l: 18,
    lv: 1,
    i: "Fromage blanc 0% 200g, kiwi 80g, fraises 80g, graines de courge 20g, amandes effilées 20g, miel 10g",
    st: ["Verser le fromage blanc dans un bol.", "Disposer les fruits coupés par-dessus.", "Parsemer de graines et amandes, finir avec le miel."],
    w: false,
    tags: ["fromage blanc", "kiwi", "fraises", "graines", "amandes", "miel"]
  },
  {
    n: "Pancakes Flocons Avoine Myrtilles",
    f: "🇺🇸",
    k: 396,
    p: 14,
    g: 58,
    l: 12,
    lv: 2,
    i: "Flocons d'avoine 100g, lait écrémé 150ml, oeuf 60g, myrtilles 80g, levure 3g, huile 8ml",
    st: ["Mixer les flocons d'avoine en farine. Mélanger avec lait, oeuf, levure.", "Cuire des petits pancakes dans une poêle avec un peu d'huile.", "Servir avec les myrtilles fraîches."],
    w: false,
    tags: ["avoine", "lait", "oeuf", "myrtilles"]
  },
  {
    n: "Omelette Blanche Champignons Épinards",
    f: "🇫🇷",
    k: 390,
    p: 34,
    g: 14,
    l: 22,
    lv: 2,
    i: "Blancs d'oeufs 200g, champignons 100g, épinards 80g, fromage de chèvre 30g, huile d'olive 10ml, herbes de Provence 2g",
    st: ["Faire sauter les champignons et épinards dans l'huile d'olive.", "Verser les blancs d'oeufs battus par-dessus.", "Cuire à feu moyen, ajouter le fromage de chèvre, plier."],
    w: false,
    tags: ["blancs d'oeuf", "champignons", "épinards", "chèvre"]
  },
  {
    n: "Bowl Açaí Banane Beurre de Cacahuète",
    f: "🇧🇷",
    k: 408,
    p: 18,
    g: 48,
    l: 16,
    lv: 1,
    i: "Pulpe d'açaí 100g, banane 100g, granola 50g, beurre de cacahuète 20g, lait d'amande 80ml",
    st: ["Mixer l'açaí avec la banane et le lait d'amande.", "Verser dans un bol.", "Garnir de granola et beurre de cacahuète."],
    w: false,
    tags: ["açaí", "banane", "granola", "cacahuète", "lait d'amande"]
  },
  {
    n: "Tartines Pain Complet Oeuf Pesto",
    f: "🇮🇹",
    k: 382,
    p: 22,
    g: 42,
    l: 14,
    lv: 1,
    i: "Pain complet 80g, oeuf dur 2x60g, pesto basilic 20g, tomate cerise 80g, roquette 20g",
    st: ["Griller le pain complet.", "Tartiner de pesto.", "Garnir de rondelles d'oeufs durs, tomates cerises et roquette."],
    w: false,
    tags: ["pain", "oeuf", "pesto", "tomate", "roquette"]
  },
  {
    n: "Chia Pudding Mangue Coco",
    f: "🇹🇭",
    k: 398,
    p: 16,
    g: 52,
    l: 14,
    lv: 1,
    i: "Graines de chia 40g, lait de coco 200ml, mangue 120g, miel 10g, noix de coco râpée 15g",
    st: ["Mélanger les graines de chia avec le lait de coco et le miel.", "Réfrigérer toute la nuit jusqu'à prise en gel.", "Servir avec la mangue coupée et la noix de coco râpée."],
    w: false,
    tags: ["chia", "lait de coco", "mangue", "miel", "coco"]
  },
  {
    n: "Pain Perdu Ricotta Fruits Rouges",
    f: "🇫🇷",
    k: 414,
    p: 26,
    g: 28,
    l: 22,
    lv: 2,
    i: "Pain brioché 80g, ricotta 100g, oeufs 2x60g, framboises 60g, sucre vanillé 5g, beurre 10g",
    st: ["Battre les oeufs, tremper le pain brioché.", "Cuire dans une poêle avec le beurre.", "Servir avec la ricotta fouettée et les framboises fraîches."],
    w: false,
    tags: ["pain brioché", "ricotta", "oeuf", "framboises", "beurre"]
  },
  {
    n: "Granola Maison Yaourt Mangue",
    f: "🇺🇸",
    k: 406,
    p: 20,
    g: 50,
    l: 14,
    lv: 2,
    i: "Flocons d'avoine 80g, miel 20g, amandes 20g, huile de coco 8g, yaourt grec 150g, mangue 100g",
    st: ["Mélanger flocons, miel, amandes et huile de coco. Étaler sur plaque.", "Cuire au four à 160°C pendant 20 min en remuant à mi-cuisson.", "Servir sur le yaourt grec avec la mangue."],
    w: false,
    tags: ["avoine", "miel", "amandes", "yaourt", "mangue"]
  },
  {
    n: "Smoothie Bowl Framboise Protéiné",
    f: "🇺🇸",
    k: 386,
    p: 18,
    g: 56,
    l: 10,
    lv: 1,
    i: "Framboises 150g, banane 100g, yaourt grec 100g, granola 60g, graines de chia 10g, miel 5g",
    st: ["Mixer les framboises, banane et yaourt grec.", "Verser dans un bol.", "Garnir de granola, graines de chia et miel."],
    w: false,
    tags: ["framboises", "banane", "yaourt", "granola", "chia"]
  },
  {
    n: "Oeufs Cocotte Tomate Épinards",
    f: "🇫🇷",
    k: 398,
    p: 32,
    g: 18,
    l: 22,
    lv: 2,
    i: "Oeufs 3x60g, épinards 100g, tomate 100g, crème légère 30ml, fromage râpé 20g, sel, poivre",
    st: ["Préchauffer le four à 180°C.", "Disposer épinards et tomate dans des ramequins, casser les oeufs par-dessus.", "Ajouter la crème et le fromage, cuire 12-15 min."],
    w: false,
    tags: ["oeuf", "épinards", "tomate", "crème", "fromage"]
  },
  {
    n: "Flocons d'Avoine Poires Cannelle",
    f: "🇫🇷",
    k: 386,
    p: 14,
    g: 60,
    l: 10,
    lv: 1,
    i: "Flocons d'avoine 90g, poire 120g, lait écrémé 250ml, cannelle 2g, cardamome 1g, miel 10g",
    st: ["Porter le lait à ébullition, verser sur les flocons.", "Laisser gonfler 5 min.", "Ajouter la poire râpée, cannelle, cardamome et miel."],
    w: false,
    tags: ["avoine", "poire", "lait", "cannelle", "miel"]
  },
  {
    n: "Pancakes Ricotta Citron",
    f: "🇮🇹",
    k: 410,
    p: 22,
    g: 40,
    l: 18,
    lv: 2,
    i: "Farine 70g, ricotta 100g, oeufs 2x60g, lait 80ml, citron zeste 5g, sucre 10g, levure 3g",
    st: ["Mélanger tous les ingrédients en pâte lisse.", "Cuire des pancakes dans une poêle antiadhésive.", "Servir avec un zeste de citron et miel."],
    w: false,
    tags: ["farine", "ricotta", "oeuf", "lait", "citron"]
  },
  {
    n: "Overnight Oats Mangue Coco",
    f: "🇹🇭",
    k: 388,
    p: 16,
    g: 54,
    l: 12,
    lv: 1,
    i: "Flocons d'avoine 80g, lait de coco 180ml, mangue 100g, noix de coco râpée 15g, miel 10g",
    st: ["Mélanger flocons d'avoine, lait de coco et miel.", "Réfrigérer une nuit.", "Garnir de mangue fraîche et noix de coco."],
    w: false,
    tags: ["avoine", "lait de coco", "mangue", "coco", "miel"]
  },
  {
    n: "Bowl Protéiné Fromage Blanc Noix",
    f: "🇫🇷",
    k: 412,
    p: 24,
    g: 34,
    l: 20,
    lv: 1,
    i: "Fromage blanc 0% 200g, noix 25g, noisettes 15g, miel 15g, cannelle 1g, pomme 80g",
    st: ["Verser le fromage blanc dans un bol.", "Couper la pomme en petits dés.", "Garnir de noix, noisettes, pomme et miel."],
    w: false,
    tags: ["fromage blanc", "noix", "noisettes", "miel", "pomme"]
  },
  {
    n: "Toast Beurre d'Amande Banane Graines",
    f: "🇺🇸",
    k: 410,
    p: 20,
    g: 42,
    l: 18,
    lv: 1,
    i: "Pain complet 80g, beurre d'amande 30g, banane 100g, graines de courge 10g, cannelle 1g, miel 5g",
    st: ["Griller le pain complet.", "Tartiner généreusement de beurre d'amande.", "Garnir de rondelles de banane, graines et un filet de miel."],
    w: false,
    tags: ["pain", "amande", "banane", "graines", "miel"]
  },
  {
    n: "Omelette Turque Menthe Feta",
    f: "🇹🇷",
    k: 416,
    p: 28,
    g: 22,
    l: 24,
    lv: 2,
    i: "Oeufs 3x60g, feta 50g, menthe fraîche 10g, tomate 80g, oignon 40g, huile d'olive 12ml",
    st: ["Battre les oeufs avec sel et menthe ciselée.", "Faire revenir oignon et tomate dans l'huile.", "Verser les oeufs, parsemer de feta, cuire jusqu'à prise."],
    w: false,
    tags: ["oeuf", "feta", "menthe", "tomate", "oignon"]
  },
  {
    n: "Bol Riz Brun Oeuf Poché Avocat",
    f: "🇯🇵",
    k: 388,
    p: 22,
    g: 48,
    l: 12,
    lv: 2,
    i: "Riz brun 80g cuit 200g, oeuf poché 60g, avocat 60g, sauce soja 10ml, sésame 5g, nori 5g",
    st: ["Cuire le riz brun.", "Pocher l'oeuf dans de l'eau frémissante.", "Disposer le riz, l'avocat tranché, l'oeuf. Arroser de sauce soja et parsemer de sésame."],
    w: false,
    tags: ["riz brun", "oeuf", "avocat", "soja", "sésame", "nori"]
  },
  {
    n: "Porridge Cacao Banane Noisette",
    f: "🇨🇭",
    k: 384,
    p: 14,
    g: 64,
    l: 8,
    lv: 1,
    i: "Flocons d'avoine 90g, lait écrémé 250ml, cacao non sucré 10g, banane 100g, noisettes 15g",
    st: ["Cuire les flocons d'avoine dans le lait.", "Incorporer le cacao en remuant.", "Garnir de banane tranchée et noisettes concassées."],
    w: false,
    tags: ["avoine", "lait", "cacao", "banane", "noisettes"]
  },
  {
    n: "Shakshuka aux Légumes Épicée",
    f: "🇲🇦",
    k: 412,
    p: 30,
    g: 28,
    l: 20,
    lv: 2,
    i: "Oeufs 4x60g, tomates 200g, poivron 80g, pois chiches 80g, harissa 10g, cumin 2g, huile d'olive 10ml",
    st: ["Faire revenir poivron et épices dans l'huile.", "Ajouter tomates et pois chiches, mijoter 10 min.", "Casser les oeufs dans la sauce, couvrir et cuire 5-6 min."],
    w: false,
    tags: ["oeuf", "tomate", "poivron", "pois chiches", "harissa"]
  },
  {
    n: "Crêpes Blé Complet Fromage Blanc Fruits",
    f: "🇫🇷",
    k: 378,
    p: 22,
    g: 50,
    l: 10,
    lv: 2,
    i: "Farine complète 80g, lait écrémé 200ml, oeuf 60g, fromage blanc 100g, fraises 80g, miel 10g",
    st: ["Préparer la pâte à crêpes avec farine, lait et oeuf.", "Cuire des crêpes fines.", "Garnir de fromage blanc, fraises et miel."],
    w: false,
    tags: ["farine", "lait", "oeuf", "fromage blanc", "fraises", "miel"]
  },
  {
    n: "Bowl Protéiné Quinoa Baies Amandes",
    f: "🇺🇸",
    k: 390,
    p: 26,
    g: 40,
    l: 14,
    lv: 1,
    i: "Quinoa 80g, yaourt grec 150g, amandes 20g, myrtilles 80g, framboises 60g, miel 10g",
    st: ["Cuire le quinoa, laisser refroidir.", "Mélanger avec le yaourt grec.", "Garnir d'amandes, myrtilles et framboises."],
    w: false,
    tags: ["quinoa", "yaourt", "amandes", "myrtilles", "framboises", "miel"]
  },
  {
    n: "Tartine Saumon Avocat Citron",
    f: "🇸🇪",
    k: 412,
    p: 20,
    g: 38,
    l: 20,
    lv: 1,
    i: "Pain complet 80g, saumon fumé 80g, avocat 80g, citron 10ml, aneth 5g, fromage blanc 30g",
    st: ["Griller le pain complet.", "Écraser l'avocat avec citron et sel.", "Tartiner d'avocat, disposer le saumon, le fromage blanc et l'aneth."],
    w: false,
    tags: ["pain", "saumon", "avocat", "citron", "aneth"]
  }
];

var lunch = [
  {
    n: "Poulet Grillé Riz Basmati",
    f: "🌍",
    k: 566,
    p: 48,
    g: 62,
    l: 14,
    lv: 1,
    i: "Blanc de poulet 200g, riz basmati 120g, huile d'olive 10ml, épices 3g, citron, persil",
    st: ["Mariner le poulet avec huile, épices et citron.", "Griller 6 min de chaque côté.", "Servir avec le riz basmati cuit et le persil."],
    w: false,
    tags: ["poulet", "riz", "citron", "persil"]
  },
  {
    n: "Saumon Quinoa Brocoli",
    f: "🌍",
    k: 596,
    p: 42,
    g: 44,
    l: 28,
    lv: 2,
    i: "Filet de saumon 200g, quinoa 90g, brocoli 150g, huile d'olive 15ml, citron, sel",
    st: ["Cuire le quinoa et le brocoli à la vapeur.", "Poêler le saumon 4 min de chaque côté.", "Servir avec un filet d'huile d'olive et citron."],
    w: false,
    tags: ["saumon", "quinoa", "brocoli", "huile"]
  },
  {
    n: "Poke Bowl Thon Avocat",
    f: "🌺",
    k: 576,
    p: 38,
    g: 52,
    l: 24,
    lv: 2,
    i: "Thon frais 180g, riz japonais 120g, avocat 80g, edamame 60g, carotte 40g, sauce soja 20ml, sésame 10g",
    st: ["Cuire le riz japonais.", "Couper le thon et l'avocat en dés.", "Assembler le bol avec tous les ingrédients, arroser de sauce soja."],
    w: false,
    tags: ["thon", "riz", "avocat", "edamame", "carotte", "soja"]
  },
  {
    n: "Steak Boeuf Patate Douce",
    f: "🇺🇸",
    k: 542,
    p: 46,
    g: 40,
    l: 22,
    lv: 2,
    i: "Steak de boeuf 200g, patate douce 200g, haricots verts 100g, huile d'olive 12ml, herbes de Provence 3g",
    st: ["Cuire la patate douce en dés au four à 200°C pendant 25 min.", "Griller le steak à feu vif 3-4 min de chaque côté.", "Accompagner de haricots verts vapeur."],
    w: false,
    tags: ["boeuf", "patate douce", "haricots verts", "huile"]
  },
  {
    n: "Salade César Poulet",
    f: "🇺🇸",
    k: 446,
    p: 44,
    g: 18,
    l: 22,
    lv: 2,
    i: "Blanc de poulet 200g, laitue romaine 150g, parmesan 30g, croûtons 30g, sauce César 30g, citron 10ml",
    st: ["Griller le poulet et le trancher.", "Préparer la laitue, les croûtons et le parmesan.", "Mélanger avec la sauce César et le jus de citron."],
    w: false,
    tags: ["poulet", "laitue", "parmesan", "croûtons", "sauce césar"]
  },
  {
    n: "Bowl Lentilles Épinards",
    f: "🇮🇳",
    k: 428,
    p: 24,
    g: 56,
    l: 12,
    lv: 2,
    i: "Lentilles vertes 120g, épinards 100g, tomate 100g, oignon 60g, cumin 2g, curcuma 2g, huile 10ml",
    st: ["Cuire les lentilles dans l'eau bouillante 20 min.", "Faire revenir oignon, tomate et épices.", "Ajouter les épinards et les lentilles, mijoter 5 min."],
    w: false,
    tags: ["lentilles", "épinards", "tomate", "oignon", "cumin", "curcuma"]
  },
  {
    n: "Harira Poulet",
    f: "🇲🇦",
    k: 412,
    p: 36,
    g: 40,
    l: 12,
    lv: 2,
    i: "Blanc de poulet 150g, pois chiches 80g, tomates 150g, céleri 50g, coriandre 10g, cumin 2g, citron, huile 8ml",
    st: ["Faire revenir le poulet avec les épices.", "Ajouter tomates, pois chiches, céleri et 600ml d'eau.", "Mijoter 25 min, finir avec coriandre fraîche et citron."],
    w: false,
    tags: ["poulet", "pois chiches", "tomate", "coriandre", "cumin"]
  },
  {
    n: "Wrap Dinde Avocat",
    f: "🇺🇸",
    k: 500,
    p: 38,
    g: 42,
    l: 20,
    lv: 1,
    i: "Tortilla blé 70g, escalope de dinde 160g, avocat 80g, laitue 30g, tomate 60g, moutarde 10g",
    st: ["Cuire la dinde à la poêle.", "Préparer les légumes.", "Assembler le wrap avec tous les ingrédients, rouler serré."],
    w: false,
    tags: ["tortilla", "dinde", "avocat", "laitue", "tomate"]
  },
  {
    n: "Risotto Poulet Champignons",
    f: "🇮🇹",
    k: 618,
    p: 42,
    g: 72,
    l: 18,
    lv: 3,
    i: "Riz arborio 150g, blanc de poulet 150g, champignons 100g, oignon 60g, parmesan 30g, bouillon 600ml, huile d'olive 10ml",
    st: ["Faire revenir l'oignon et le poulet.", "Ajouter le riz, nacrer 2 min.", "Incorporer le bouillon louche par louche en remuant 20 min. Finir avec parmesan."],
    w: false,
    tags: ["riz", "poulet", "champignons", "parmesan", "oignon"]
  },
  {
    n: "Pad Thaï Crevettes",
    f: "🇹🇭",
    k: 470,
    p: 32,
    g: 54,
    l: 14,
    lv: 2,
    i: "Nouilles de riz 120g, crevettes 150g, oeufs 2x60g, cacahuètes 20g, germes de soja 60g, sauce tamarin 20ml, huile 8ml",
    st: ["Tremper les nouilles de riz dans l'eau froide 30 min.", "Poêler les crevettes, ajouter les oeufs brouillés.", "Ajouter les nouilles, la sauce, les germes de soja. Garnir de cacahuètes."],
    w: false,
    tags: ["nouilles", "crevettes", "oeuf", "cacahuètes", "soja", "tamarin"]
  },
  {
    n: "Shawarma Poulet Semoule",
    f: "🌍",
    k: 562,
    p: 48,
    g: 52,
    l: 18,
    lv: 2,
    i: "Blanc de poulet 200g, semoule 120g, yaourt 60g, épices shawarma 5g, tomate 60g, concombre 40g, ail 5g",
    st: ["Mariner le poulet dans les épices, yaourt et ail au moins 30 min.", "Cuire le poulet à la poêle ou au four 20 min.", "Servir avec la semoule cuite et les légumes."],
    w: false,
    tags: ["poulet", "semoule", "yaourt", "tomate", "concombre", "ail"]
  },
  {
    n: "Bibimbap Boeuf",
    f: "🇰🇷",
    k: 546,
    p: 38,
    g: 58,
    l: 18,
    lv: 3,
    i: "Boeuf haché 150g, riz japonais 120g, épinards 80g, carotte 60g, courgette 60g, oeuf 60g, sauce gochujang 15g, huile de sésame 8ml",
    st: ["Cuire le riz.", "Poêler le boeuf haché avec la sauce.", "Assembler le bol avec riz, légumes sautés séparément, boeuf et oeuf au plat. Finir avec huile de sésame."],
    w: false,
    tags: ["boeuf", "riz", "épinards", "carotte", "courgette", "oeuf", "sésame"]
  },
  {
    n: "Ceviche Cabillaud",
    f: "🇵🇪",
    k: 388,
    p: 36,
    g: 16,
    l: 20,
    lv: 2,
    i: "Cabillaud frais 200g, citron vert 60ml, avocat 80g, oignon rouge 40g, coriandre 10g, piment 3g, maïs 40g",
    st: ["Couper le cabillaud en petits dés.", "Mariner dans le jus de citron vert 15 min jusqu'à opacification.", "Mélanger avec avocat, oignon, coriandre et piment."],
    w: false,
    tags: ["cabillaud", "citron", "avocat", "oignon", "coriandre", "maïs"]
  },
  {
    n: "Tikka Masala Poulet",
    f: "🇮🇳",
    k: 516,
    p: 46,
    g: 38,
    l: 20,
    lv: 3,
    i: "Blanc de poulet 200g, yaourt 80g, tomates 150g, crème 40ml, oignon 60g, tikka masala 10g, riz basmati 80g",
    st: ["Mariner le poulet dans yaourt et épices.", "Cuire l'oignon, ajouter tomates et épices, incorporer la crème.", "Ajouter le poulet grillé, mijoter 10 min. Servir avec riz basmati."],
    w: false,
    tags: ["poulet", "yaourt", "tomate", "crème", "riz", "tikka masala"]
  },
  {
    n: "Couscous Royal",
    f: "🇲🇦",
    k: 626,
    p: 48,
    g: 68,
    l: 18,
    lv: 3,
    i: "Semoule 150g, agneau 150g, merguez de poulet 80g, courgette 80g, carotte 80g, pois chiches 60g, bouillon 300ml, ras el hanout 5g",
    st: ["Cuire la semoule selon les instructions.", "Braiser l'agneau avec les épices et légumes.", "Assembler avec les merguez grillées et un peu de harissa."],
    w: false,
    tags: ["semoule", "agneau", "merguez", "courgette", "carotte", "pois chiches"]
  },
  {
    n: "Ramen Poulet Maison",
    f: "🇯🇵",
    k: 504,
    p: 42,
    g: 48,
    l: 16,
    lv: 3,
    i: "Nouilles ramen 120g, blanc de poulet 180g, bouillon de poulet 600ml, oeuf 60g, nori 5g, oignons verts 20g, sauce soja 20ml, huile de sésame 8ml",
    st: ["Cuire le poulet dans le bouillon avec sauce soja.", "Cuire les nouilles séparément.", "Assembler: nouilles, poulet effiloché, oeuf mollet, nori et oignons verts."],
    w: false,
    tags: ["nouilles", "poulet", "bouillon", "oeuf", "nori", "soja"]
  },
  {
    n: "Osso Bucco Veau",
    f: "🇮🇹",
    k: 570,
    p: 52,
    g: 32,
    l: 26,
    lv: 4,
    i: "Jarret de veau 250g, tomates 150g, oignon 60g, carotte 60g, céleri 40g, bouillon 200ml, gremolata 10g, huile d'olive 12ml",
    st: ["Fariner et dorer les jarrets de veau dans l'huile.", "Ajouter les légumes, tomates et bouillon.", "Braiser 1h30 à feu doux. Finir avec la gremolata."],
    w: false,
    tags: ["veau", "tomate", "oignon", "carotte", "céleri"]
  },
  {
    n: "Bowl Poulet Patate Douce Avocat",
    f: "🇺🇸",
    k: 526,
    p: 38,
    g: 44,
    l: 22,
    lv: 2,
    i: "Poulet grillé 170g, patate douce rôtie 150g, avocat 60g, épinards 60g, pois chiches 60g, tahini 15g",
    st: ["Cuire la patate douce au four à 200°C.", "Griller le poulet assaisonné.", "Assembler le bowl avec tous les ingrédients, drizzler de tahini."],
    w: false,
    tags: ["poulet", "patate douce", "avocat", "épinards", "pois chiches", "tahini"]
  },
  {
    n: "Dahl Lentilles Corail Coco",
    f: "🇮🇳",
    k: 488,
    p: 40,
    g: 46,
    l: 16,
    lv: 2,
    i: "Lentilles corail 150g, lait de coco 100ml, tomates 100g, oignon 60g, gingembre 10g, curcuma 2g, cumin 2g, huile 10ml",
    st: ["Faire revenir oignon, gingembre et épices.", "Ajouter lentilles, tomates et lait de coco.", "Cuire 25 min jusqu'à consistance crémeuse."],
    w: false,
    tags: ["lentilles", "lait de coco", "tomate", "oignon", "gingembre", "curcuma"]
  },
  {
    n: "Filet Cabillaud Légumes Rôtis",
    f: "🇵🇹",
    k: 516,
    p: 44,
    g: 40,
    l: 20,
    lv: 2,
    i: "Filet de cabillaud 200g, poivron rouge 100g, courgette 100g, tomate 100g, pomme de terre 100g, huile d'olive 12ml, herbes 3g",
    st: ["Couper les légumes, assaisonner avec huile et herbes, rôtir 25 min à 200°C.", "Assaisonner le cabillaud, déposer sur les légumes.", "Cuire encore 15 min."],
    w: false,
    tags: ["cabillaud", "poivron", "courgette", "tomate", "pomme de terre"]
  },
  {
    n: "Bowl Boeuf Coréen Riz Sésame",
    f: "🇰🇷",
    k: 512,
    p: 42,
    g: 50,
    l: 16,
    lv: 3,
    i: "Boeuf 180g, riz japonais 120g, sauce soja 20ml, ail 5g, gingembre 5g, poire asiatique 40g, huile de sésame 8ml, sésame 8g",
    st: ["Mariner le boeuf dans sauce soja, ail, gingembre et poire râpée.", "Poêler à feu vif.", "Servir sur le riz avec huile de sésame et sésame grillé."],
    w: false,
    tags: ["boeuf", "riz", "soja", "ail", "gingembre", "sésame"]
  },
  {
    n: "Tajine Agneau Légumes",
    f: "🇲🇦",
    k: 494,
    p: 36,
    g: 56,
    l: 14,
    lv: 3,
    i: "Agneau 180g, courgette 100g, carotte 100g, pois chiches 80g, semoule 80g, ras el hanout 5g, coriandre 10g",
    st: ["Dorer l'agneau avec les épices.", "Ajouter les légumes et pois chiches, couvrir d'eau.", "Mijoter 45 min. Servir avec la semoule et coriandre fraîche."],
    w: false,
    tags: ["agneau", "courgette", "carotte", "pois chiches", "semoule", "coriandre"]
  },
  {
    n: "Poulet Teriyaki Riz Brocoli",
    f: "🇯🇵",
    k: 506,
    p: 38,
    g: 48,
    l: 18,
    lv: 2,
    i: "Blanc de poulet 180g, riz 120g, brocoli 150g, sauce teriyaki 30ml, sésame 8g, oignons verts 15g",
    st: ["Mariner le poulet dans la sauce teriyaki.", "Griller le poulet.", "Servir avec le riz vapeur et le brocoli. Garnir de sésame."],
    w: false,
    tags: ["poulet", "riz", "brocoli", "teriyaki", "sésame"]
  },
  {
    n: "Salade Niçoise Thon",
    f: "🇫🇷",
    k: 536,
    p: 44,
    g: 36,
    l: 24,
    lv: 1,
    i: "Thon en conserve 180g, haricots verts 100g, pomme de terre 120g, oeuf dur 60g, tomate 80g, olives 20g, huile d'olive 12ml",
    st: ["Cuire les haricots verts et pommes de terre.", "Assembler la salade avec tous les ingrédients.", "Assaisonner d'huile d'olive et sel."],
    w: false,
    tags: ["thon", "haricots verts", "pomme de terre", "oeuf", "tomate", "olives"]
  },
  {
    n: "Curry Rouge Poulet Coco",
    f: "🇹🇭",
    k: 522,
    p: 46,
    g: 44,
    l: 18,
    lv: 3,
    i: "Blanc de poulet 200g, lait de coco 100ml, pâte de curry rouge 20g, poivron 80g, aubergine 80g, riz jasmin 100g",
    st: ["Faire revenir la pâte de curry dans une poêle.", "Ajouter le poulet, puis le lait de coco et les légumes.", "Mijoter 15 min. Servir avec riz jasmin."],
    w: false,
    tags: ["poulet", "lait de coco", "curry rouge", "poivron", "aubergine", "riz"]
  },
  {
    n: "Salade Quinoa Feta Légumes Grillés",
    f: "🇬🇷",
    k: 512,
    p: 40,
    g: 52,
    l: 16,
    lv: 2,
    i: "Quinoa 100g, feta 80g, courgette grillée 100g, poivron rouge 80g, roquette 40g, pignons 15g, vinaigrette citron 15ml",
    st: ["Cuire le quinoa.", "Griller les légumes.", "Assembler avec la feta, roquette, pignons et vinaigrette."],
    w: false,
    tags: ["quinoa", "feta", "courgette", "poivron", "roquette", "pignons"]
  },
  {
    n: "Tacos Poulet Guacamole",
    f: "🇲🇽",
    k: 524,
    p: 42,
    g: 44,
    l: 20,
    lv: 2,
    i: "Blanc de poulet 180g, tortillas 2x35g, guacamole 60g, salsa 40g, chou rouge 40g, citron vert 10ml, épices 3g",
    st: ["Cuire le poulet avec les épices.", "Préparer le guacamole et la salsa.", "Assembler les tacos avec poulet, guacamole, salsa et chou."],
    w: false,
    tags: ["poulet", "tortilla", "avocat", "salsa", "chou"]
  },
  {
    n: "Bowl Falafel Houmous Taboulé",
    f: "🇱🇧",
    k: 492,
    p: 36,
    g: 60,
    l: 12,
    lv: 3,
    i: "Falafels 120g, houmous 80g, taboulé 100g, pain pita 60g, tzatziki 40g, tomate 60g",
    st: ["Cuire les falafels au four ou à la poêle.", "Préparer le taboulé avec persil, boulgour et tomates.", "Assembler le bowl avec houmous, falafels et taboulé."],
    w: false,
    tags: ["falafel", "houmous", "taboulé", "pita", "persil", "boulgour"]
  },
  {
    n: "Poisson Grillé Salsa Mangue",
    f: "🇨🇴",
    k: 504,
    p: 44,
    g: 46,
    l: 16,
    lv: 2,
    i: "Filet de daurade 200g, mangue 120g, avocat 60g, oignon rouge 30g, coriandre 10g, riz 90g, citron vert 15ml",
    st: ["Griller le filet de daurade.", "Préparer la salsa avec mangue, avocat, oignon et coriandre.", "Servir avec le riz et la salsa."],
    w: false,
    tags: ["daurade", "mangue", "avocat", "coriandre", "riz"]
  },
  {
    n: "Chicken Tikka Naan Yogurt",
    f: "🇮🇳",
    k: 514,
    p: 40,
    g: 48,
    l: 18,
    lv: 3,
    i: "Poulet 180g, naan 100g, yaourt 80g, oignon 60g, tomate 80g, tikka masala 8g, huile 8ml",
    st: ["Mariner le poulet dans yaourt et épices.", "Cuire le poulet grillé.", "Servir avec naan chaud et sauce au yaourt."],
    w: false,
    tags: ["poulet", "naan", "yaourt", "tomate", "tikka masala"]
  },
  {
    n: "Saumon Teriyaki Riz Edamame",
    f: "🇯🇵",
    k: 514,
    p: 38,
    g: 50,
    l: 18,
    lv: 2,
    i: "Filet de saumon 180g, riz japonais 120g, edamame 80g, sauce teriyaki 25ml, sésame 8g, gingembre 5g",
    st: ["Mariner le saumon dans la sauce teriyaki.", "Poêler le saumon 4 min de chaque côté.", "Servir avec riz et edamame. Parsemer de sésame."],
    w: false,
    tags: ["saumon", "riz", "edamame", "teriyaki", "sésame"]
  },
  {
    n: "Boeuf Haché Légumes Wok",
    f: "🇨🇳",
    k: 516,
    p: 42,
    g: 42,
    l: 20,
    lv: 2,
    i: "Boeuf haché 180g, brocoli 100g, poivron 80g, carotte 60g, sauce huître halal 20ml, riz 100g, ail 5g",
    st: ["Poêler le boeuf haché à feu vif.", "Ajouter les légumes et l'ail.", "Incorporer la sauce, servir avec le riz."],
    w: false,
    tags: ["boeuf", "brocoli", "poivron", "carotte", "sauce huître", "riz"]
  },
  {
    n: "Souvlaki Poulet Tzatziki",
    f: "🇬🇷",
    k: 534,
    p: 46,
    g: 38,
    l: 22,
    lv: 2,
    i: "Poulet 200g, pain pita 80g, tzatziki 60g, tomate 60g, oignon rouge 40g, roquette 30g, épices grecques 5g",
    st: ["Mariner le poulet avec épices et huile d'olive.", "Griller en brochettes.", "Servir dans le pita avec tzatziki, tomate et oignon."],
    w: false,
    tags: ["poulet", "pita", "tzatziki", "tomate", "oignon", "roquette"]
  },
  {
    n: "Burritos Boeuf Haricots Noirs",
    f: "🇲🇽",
    k: 504,
    p: 40,
    g: 50,
    l: 16,
    lv: 3,
    i: "Boeuf haché 150g, haricots noirs 100g, tortilla blé 80g, maïs 60g, salsa 40g, fromage râpé 30g, épices 5g",
    st: ["Cuire le boeuf haché avec épices et oignon.", "Chauffer les haricots noirs.", "Assembler le burrito, rouler, griller 2 min."],
    w: false,
    tags: ["boeuf", "haricots noirs", "tortilla", "maïs", "salsa", "fromage"]
  },
  {
    n: "Pho Bo Authentique",
    f: "🇻🇳",
    k: 522,
    p: 42,
    g: 48,
    l: 18,
    lv: 3,
    i: "Boeuf 180g, nouilles de riz 120g, bouillon pho 600ml, oignon brûlé 40g, gingembre 10g, basilic 10g, germes de soja 60g",
    st: ["Préparer le bouillon avec os de boeuf, oignon brûlé et épices 2h.", "Cuire les nouilles.", "Assembler: nouilles, boeuf, bouillon chaud, herbes et germes."],
    w: false,
    tags: ["boeuf", "nouilles", "bouillon", "gingembre", "basilic", "soja"]
  },
  {
    n: "Gratin Poulet Légumes Béchamel",
    f: "🇫🇷",
    k: 534,
    p: 44,
    g: 40,
    l: 22,
    lv: 3,
    i: "Poulet 200g, courgette 100g, poivron 80g, béchamel légère 100ml, fromage râpé 40g, pâtes 80g",
    st: ["Cuire les pâtes al dente.", "Poêler poulet et légumes.", "Assembler, napper de béchamel, gratiner 20 min à 180°C."],
    w: false,
    tags: ["poulet", "courgette", "poivron", "béchamel", "fromage", "pâtes"]
  },
  {
    n: "Nasi Goreng Poulet",
    f: "🇮🇩",
    k: 484,
    p: 38,
    g: 56,
    l: 12,
    lv: 2,
    i: "Riz cuit 200g, poulet 150g, oeuf 60g, oignon 60g, sauce soja 15ml, piment 3g, ail 5g, huile 8ml",
    st: ["Poêler le riz cuit avec ail et oignon.", "Ajouter le poulet en dés, oeuf et sauce soja.", "Incorporer le piment. Servir avec oeuf au plat."],
    w: false,
    tags: ["riz", "poulet", "oeuf", "soja", "ail", "oignon"]
  },
  {
    n: "Wrap Falafel Légumes Houmous",
    f: "🇱🇧",
    k: 516,
    p: 40,
    g: 44,
    l: 20,
    lv: 2,
    i: "Falafels 140g, tortilla 80g, houmous 60g, taboulé 80g, laitue 30g, tomate 60g, oignon rouge 30g",
    st: ["Cuire les falafels.", "Tartiner la tortilla de houmous.", "Garnir de falafels, taboulé, laitue et tomate. Rouler."],
    w: false,
    tags: ["falafel", "tortilla", "houmous", "taboulé", "laitue", "tomate"]
  },
  {
    n: "Poulet Mafé Sénégalais",
    f: "🇸🇳",
    k: 506,
    p: 36,
    g: 50,
    l: 18,
    lv: 3,
    i: "Poulet 180g, beurre de cacahuète 30g, tomates 150g, oignon 60g, patate douce 100g, riz 80g, ail 5g",
    st: ["Faire revenir le poulet, oignon et ail.", "Ajouter tomates, beurre de cacahuète dilué et patate douce.", "Mijoter 30 min. Servir avec riz."],
    w: false,
    tags: ["poulet", "cacahuète", "tomate", "patate douce", "riz"]
  },
  {
    n: "Salade Thaï Boeuf Grillé",
    f: "🇹🇭",
    k: 514,
    p: 42,
    g: 46,
    l: 18,
    lv: 2,
    i: "Boeuf 180g, nouilles de riz 100g, concombre 60g, carotte 60g, cacahuètes 20g, menthe 10g, sauce fish halal 15ml, citron vert 20ml",
    st: ["Griller le boeuf saignant, trancher fin.", "Cuire les nouilles.", "Assembler avec légumes, herbes, cacahuètes et sauce citron."],
    w: false,
    tags: ["boeuf", "nouilles", "concombre", "carotte", "cacahuètes", "menthe"]
  },
  {
    n: "Poulet Rôti Pommes de Terre",
    f: "🇫🇷",
    k: 526,
    p: 44,
    g: 38,
    l: 22,
    lv: 3,
    i: "Cuisses de poulet 220g, pommes de terre 200g, oignon 60g, ail 10g, herbes de Provence 3g, huile d'olive 10ml",
    st: ["Assaisonner le poulet avec herbes, ail et huile.", "Disposer avec pommes de terre en rondelles.", "Cuire au four 40 min à 200°C."],
    w: false,
    tags: ["poulet", "pomme de terre", "oignon", "ail", "herbes de Provence"]
  },
  {
    n: "Lomo Saltado Boeuf",
    f: "🇵🇪",
    k: 508,
    p: 40,
    g: 42,
    l: 20,
    lv: 3,
    i: "Boeuf 180g, pommes de terre 150g, tomate 80g, oignon rouge 60g, sauce soja 15ml, coriandre 10g, riz 80g",
    st: ["Faire sauter le boeuf à feu très vif.", "Ajouter oignon, tomate et sauce soja.", "Incorporer les frites maison et coriandre. Servir avec riz."],
    w: false,
    tags: ["boeuf", "pomme de terre", "tomate", "oignon", "soja", "coriandre"]
  },
  {
    n: "Poulet Korma Riz Basmati",
    f: "🇮🇳",
    k: 486,
    p: 38,
    g: 52,
    l: 14,
    lv: 3,
    i: "Poulet 180g, yaourt 80g, oignon 60g, amandes 20g, crème légère 40ml, épices korma 8g, riz basmati 100g",
    st: ["Mariner le poulet dans yaourt et épices.", "Préparer la sauce korma avec oignon, amandes et crème.", "Mijoter 20 min. Servir avec riz basmati."],
    w: false,
    tags: ["poulet", "yaourt", "amandes", "crème", "riz", "korma"]
  },
  {
    n: "Keftah Boeuf Tomate Herbes",
    f: "🇲🇦",
    k: 524,
    p: 42,
    g: 44,
    l: 20,
    lv: 2,
    i: "Boeuf haché 200g, tomates 150g, oignon 60g, persil 10g, cumin 2g, paprika 2g, semoule 100g, harissa 10g",
    st: ["Préparer les keftah avec boeuf, oignon et épices.", "Griller les keftah ou cuire à la poêle.", "Servir avec semoule et sauce tomate épicée."],
    w: false,
    tags: ["boeuf", "tomate", "oignon", "persil", "semoule", "harissa"]
  },
  {
    n: "Wok Crevettes Légumes Riz",
    f: "🇨🇳",
    k: 524,
    p: 46,
    g: 40,
    l: 20,
    lv: 2,
    i: "Crevettes 200g, brocoli 100g, carotte 60g, champignons 60g, riz 100g, sauce soja 15ml, ail 5g, gingembre 5g, huile 10ml",
    st: ["Poêler les crevettes à feu vif.", "Ajouter les légumes, ail et gingembre.", "Incorporer la sauce soja. Servir avec riz vapeur."],
    w: false,
    tags: ["crevettes", "brocoli", "carotte", "champignons", "riz", "soja"]
  },
  {
    n: "Hamburger Dinde Maison",
    f: "🇺🇸",
    k: 534,
    p: 44,
    g: 40,
    l: 22,
    lv: 3,
    i: "Dinde hachée 180g, pain burger complet 80g, tomate 60g, laitue 30g, oignon 30g, fromage 30g, moutarde 10g",
    st: ["Façonner le steak de dinde, assaisonner.", "Griller 5 min de chaque côté.", "Assembler le burger avec tous les ingrédients."],
    w: false,
    tags: ["dinde", "pain", "tomate", "laitue", "oignon", "fromage"]
  },
  {
    n: "Poêlée Saumon Épinards Quinoa",
    f: "🇸🇪",
    k: 506,
    p: 40,
    g: 46,
    l: 18,
    lv: 2,
    i: "Saumon 180g, épinards 100g, quinoa 100g, ail 5g, huile d'olive 10ml, citron 15ml, câpres 15g",
    st: ["Cuire le quinoa.", "Poêler le saumon côté peau.", "Faire sauter les épinards avec ail, citron et câpres. Servir ensemble."],
    w: false,
    tags: ["saumon", "épinards", "quinoa", "ail", "citron", "câpres"]
  },
  {
    n: "Poulet Piri Piri Riz Coriandre",
    f: "🇵🇹",
    k: 506,
    p: 38,
    g: 48,
    l: 18,
    lv: 2,
    i: "Poulet 180g, riz 110g, piri piri 15g, ail 5g, citron 15ml, coriandre 10g, huile d'olive 8ml",
    st: ["Mariner le poulet dans la sauce piri piri, ail et citron.", "Griller au four ou sur la braise.", "Servir avec riz vapeur et coriandre fraîche."],
    w: false,
    tags: ["poulet", "riz", "piri piri", "ail", "citron", "coriandre"]
  },
  {
    n: "Enchiladas Poulet Sauce Tomate",
    f: "🇲🇽",
    k: 524,
    p: 42,
    g: 44,
    l: 20,
    lv: 3,
    i: "Poulet 180g, tortillas 2x40g, sauce enchilada 100g, fromage râpé 40g, haricots noirs 60g, crème 20ml",
    st: ["Cuire le poulet effiloché avec sauce.", "Rouler dans les tortillas.", "Napper de sauce et fromage, cuire 20 min à 180°C."],
    w: false,
    tags: ["poulet", "tortilla", "sauce tomate", "fromage", "haricots noirs"]
  },
  {
    n: "Bol Buddha Légumes Tofu",
    f: "🇯🇵",
    k: 496,
    p: 40,
    g: 48,
    l: 16,
    lv: 2,
    i: "Tofu ferme 200g, riz brun 120g, edamame 80g, carotte 60g, avocat 60g, graines de sésame 10g, sauce tahini 20g",
    st: ["Cuire le riz brun.", "Poêler le tofu jusqu'à dorure.", "Assembler le bol avec tous les ingrédients et sauce tahini."],
    w: false,
    tags: ["tofu", "riz brun", "edamame", "carotte", "avocat", "sésame", "tahini"]
  }
];

var snack = [
  {
    n: "Yaourt Grec Amandes Miel",
    f: "🇬🇷",
    k: 258,
    p: 22,
    g: 20,
    l: 10,
    lv: 1,
    i: "Yaourt grec 0% 200g, amandes 20g, miel 15g",
    st: ["Verser le yaourt dans un bol.", "Parsemer d'amandes.", "Drizzler de miel."],
    w: false,
    tags: ["yaourt", "amandes", "miel"]
  },
  {
    n: "Pomme Beurre d'Amande",
    f: "🇺🇸",
    k: 252,
    p: 6,
    g: 30,
    l: 12,
    lv: 1,
    i: "Pomme 180g, beurre d'amande 30g",
    st: ["Trancher la pomme en quartiers.", "Servir avec le beurre d'amande pour tremper."],
    w: false,
    tags: ["pomme", "amande"]
  },
  {
    n: "Oeufs Durs Crudités",
    f: "🌍",
    k: 222,
    p: 16,
    g: 8,
    l: 14,
    lv: 1,
    i: "Oeufs durs 2x60g, carotte 80g, concombre 80g, tomate cerise 60g, sel, poivre",
    st: ["Cuire les oeufs 10 min dans l'eau bouillante.", "Laisser refroidir, écaler.", "Servir avec les crudités."],
    w: false,
    tags: ["oeuf", "carotte", "concombre", "tomate"]
  },
  {
    n: "Dattes Fourrées Amandes",
    f: "🌍",
    k: 244,
    p: 5,
    g: 38,
    l: 8,
    lv: 1,
    i: "Dattes Medjool 80g, amandes entières 20g",
    st: ["Dénoyauter les dattes.", "Fourrer chaque datte d'une amande entière.", "Servir à température ambiante."],
    w: false,
    tags: ["dattes", "amandes"]
  },
  {
    n: "Edamame Citron Sel",
    f: "🇯🇵",
    k: 184,
    p: 16,
    g: 12,
    l: 8,
    lv: 1,
    i: "Edamame 200g, citron 15ml, fleur de sel 2g",
    st: ["Cuire les edamame dans l'eau bouillante salée 5 min.", "Égoutter et arroser de jus de citron.", "Parsemer de fleur de sel."],
    w: false,
    tags: ["edamame", "citron"]
  },
  {
    n: "Houmous Crudités",
    f: "🇱🇧",
    k: 288,
    p: 10,
    g: 26,
    l: 16,
    lv: 1,
    i: "Houmous 100g, carotte 80g, céleri 60g, concombre 60g, poivron rouge 60g",
    st: ["Couper les légumes en bâtonnets.", "Disposer autour du houmous.", "Déguster comme snack."],
    w: false,
    tags: ["houmous", "carotte", "céleri", "concombre", "poivron"]
  },
  {
    n: "Energy Balls Dattes Avoine",
    f: "🇺🇸",
    k: 366,
    p: 12,
    g: 48,
    l: 14,
    lv: 1,
    i: "Flocons d'avoine 80g, dattes dénoyautées 80g, beurre d'amande 25g, graines de chia 10g, cacao 10g",
    st: ["Mixer les dattes en pâte.", "Mélanger avec avoine, beurre d'amande, chia et cacao.", "Former des boules et réfrigérer 30 min."],
    w: false,
    tags: ["avoine", "dattes", "amande", "chia", "cacao"]
  },
  {
    n: "Tartine Ricotta Figues",
    f: "🇮🇹",
    k: 298,
    p: 14,
    g: 38,
    l: 10,
    lv: 1,
    i: "Pain complet 60g, ricotta 80g, figues fraîches 80g, miel 10g, noix 10g",
    st: ["Griller le pain complet.", "Tartiner de ricotta.", "Garnir de figues tranchées, noix et miel."],
    w: false,
    tags: ["pain", "ricotta", "figues", "miel", "noix"]
  },
  {
    n: "Onigiri Thon Sésame",
    f: "🇯🇵",
    k: 302,
    p: 20,
    g: 42,
    l: 6,
    lv: 2,
    i: "Riz japonais 120g, thon en conserve 80g, sésame 8g, nori 10g, sauce soja 8ml",
    st: ["Cuire le riz japonais.", "Mélanger le thon avec un peu de sauce soja.", "Former des triangles de riz farcis de thon, envelopper de nori."],
    w: false,
    tags: ["riz", "thon", "sésame", "nori", "soja"]
  },
  {
    n: "Shake Whey Banane Cacahuète",
    f: "🥤",
    k: 388,
    p: 36,
    g: 34,
    l: 12,
    lv: 1,
    i: "Whey protéine vanille 40g, banane 100g, beurre de cacahuète 20g, lait écrémé 250ml",
    st: ["Mettre tous les ingrédients dans le blender.", "Mixer jusqu'à consistance lisse.", "Servir immédiatement."],
    w: true,
    tags: ["whey", "banane", "cacahuète", "lait"]
  },
  {
    n: "Shake Whey Choco Banane",
    f: "🥤",
    k: 352,
    p: 32,
    g: 38,
    l: 8,
    lv: 1,
    i: "Whey protéine chocolat 35g, banane 100g, cacao 10g, lait écrémé 300ml",
    st: ["Mixer tous les ingrédients.", "Ajouter des glaçons si désiré.", "Servir frais."],
    w: true,
    tags: ["whey", "banane", "cacao", "lait"]
  },
  {
    n: "Shake Whey Avoine Miel",
    f: "🥤",
    k: 434,
    p: 34,
    g: 52,
    l: 10,
    lv: 1,
    i: "Whey protéine 35g, flocons d'avoine 60g, miel 20g, lait écrémé 300ml, banane 50g",
    st: ["Mixer tous les ingrédients dans le blender.", "Ajouter des glaçons.", "Servir immédiatement."],
    w: true,
    tags: ["whey", "avoine", "miel", "lait", "banane"]
  },
  {
    n: "Smoothie Whey Mangue Coco",
    f: "🥤",
    k: 378,
    p: 30,
    g: 42,
    l: 10,
    lv: 1,
    i: "Whey protéine vanille 30g, mangue 150g, lait de coco 150ml, glaçons 100g",
    st: ["Mixer la mangue avec le lait de coco.", "Ajouter la whey protéine et les glaçons.", "Mixer jusqu'à consistance lisse."],
    w: true,
    tags: ["whey", "mangue", "lait de coco"]
  },
  {
    n: "Mug Cake Whey 2min",
    f: "🥤",
    k: 280,
    p: 28,
    g: 24,
    l: 8,
    lv: 1,
    i: "Whey protéine chocolat 30g, farine d'avoine 30g, oeuf 60g, lait écrémé 30ml, levure 2g",
    st: ["Mélanger tous les ingrédients dans un mug.", "Cuire 2 min au micro-ondes.", "Laisser reposer 1 min avant de déguster."],
    w: true,
    tags: ["whey", "avoine", "oeuf", "lait"]
  },
  {
    n: "Fromage Blanc Fruits Rouges Graines",
    f: "🇫🇷",
    k: 234,
    p: 12,
    g: 24,
    l: 10,
    lv: 1,
    i: "Fromage blanc 0% 150g, framboises 60g, myrtilles 40g, graines de tournesol 15g, miel 5g",
    st: ["Verser le fromage blanc dans un bol.", "Ajouter les fruits rouges.", "Parsemer de graines et miel."],
    w: false,
    tags: ["fromage blanc", "framboises", "myrtilles", "graines", "miel"]
  },
  {
    n: "Banana Bread Protéiné",
    f: "🇺🇸",
    k: 270,
    p: 8,
    g: 28,
    l: 14,
    lv: 2,
    i: "Banane 100g, farine avoine 60g, oeuf 60g, noix 25g, miel 10g, levure 3g",
    st: ["Écraser la banane, mélanger avec oeuf, farine et miel.", "Ajouter les noix et la levure.", "Cuire 35 min à 180°C. Couper en tranches."],
    w: false,
    tags: ["banane", "avoine", "oeuf", "noix", "miel"]
  },
  {
    n: "Yaourt Grec Granola Fruits Secs",
    f: "🇬🇷",
    k: 236,
    p: 14,
    g: 18,
    l: 12,
    lv: 1,
    i: "Yaourt grec 150g, granola 30g, abricots secs 20g, noix 15g",
    st: ["Verser le yaourt dans un bol.", "Garnir de granola, abricots et noix."],
    w: false,
    tags: ["yaourt", "granola", "abricots", "noix"]
  },
  {
    n: "Energy Balls Cacao Noisette",
    f: "🇮🇹",
    k: 250,
    p: 6,
    g: 34,
    l: 10,
    lv: 1,
    i: "Flocons d'avoine 60g, dattes 60g, cacao 10g, noisettes 20g, miel 10g",
    st: ["Mixer les dattes avec les noisettes.", "Incorporer avoine, cacao et miel.", "Former des boules et réfrigérer."],
    w: false,
    tags: ["avoine", "dattes", "cacao", "noisettes", "miel"]
  },
  {
    n: "Noix Mélangées Fruits Secs",
    f: "🌍",
    k: 254,
    p: 10,
    g: 22,
    l: 14,
    lv: 1,
    i: "Amandes 25g, noix de cajou 20g, pistaches 15g, cranberries 20g, abricots secs 20g",
    st: ["Mélanger toutes les noix et fruits secs.", "Portions pré-dosées dans un sachet.", "Consommer comme en-cas."],
    w: false,
    tags: ["amandes", "cajou", "pistaches", "cranberries", "abricots"]
  },
  {
    n: "Galette de Riz Beurre Cacahuète Banane",
    f: "🇺🇸",
    k: 250,
    p: 8,
    g: 32,
    l: 10,
    lv: 1,
    i: "Galettes de riz 3x9g, beurre de cacahuète 25g, banane 80g",
    st: ["Tartiner les galettes de riz de beurre de cacahuète.", "Garnir de rondelles de banane."],
    w: false,
    tags: ["riz soufflé", "cacahuète", "banane"]
  },
  {
    n: "Skyr Myrtilles Cannelle",
    f: "🇮🇸",
    k: 244,
    p: 18,
    g: 16,
    l: 12,
    lv: 1,
    i: "Skyr 200g, myrtilles 80g, cannelle 1g, noix 15g, miel 5g",
    st: ["Verser le skyr dans un bol.", "Garnir de myrtilles, noix et cannelle.", "Drizzler de miel."],
    w: false,
    tags: ["skyr", "myrtilles", "cannelle", "noix", "miel"]
  },
  {
    n: "Tartines Pain Complet Ricotta Tomate",
    f: "🇮🇹",
    k: 242,
    p: 12,
    g: 26,
    l: 10,
    lv: 1,
    i: "Pain complet 50g, ricotta 60g, tomate 80g, basilic 5g, huile d'olive 8ml",
    st: ["Griller le pain.", "Tartiner de ricotta.", "Garnir de tomate, basilic et huile d'olive."],
    w: false,
    tags: ["pain", "ricotta", "tomate", "basilic", "huile"]
  },
  {
    n: "Boisson Protéinée Kéfir Fruits",
    f: "🇹🇷",
    k: 234,
    p: 16,
    g: 20,
    l: 10,
    lv: 1,
    i: "Kéfir 200ml, banane 60g, fraises 80g, miel 5g",
    st: ["Mixer le kéfir avec banane et fraises.", "Ajouter le miel.", "Servir frais."],
    w: false,
    tags: ["kéfir", "banane", "fraises", "miel"]
  },
  {
    n: "Compote Maison Pomme Poire Cannelle",
    f: "🇫🇷",
    k: 256,
    p: 10,
    g: 36,
    l: 8,
    lv: 1,
    i: "Pomme 150g, poire 100g, yaourt grec 100g, cannelle 2g, graines de courge 15g",
    st: ["Cuire pomme et poire avec cannelle jusqu'à consistance de compote.", "Laisser refroidir.", "Servir avec yaourt grec et graines."],
    w: false,
    tags: ["pomme", "poire", "yaourt", "cannelle", "graines"]
  },
  {
    n: "Crackers Sarrasin Thon Avocat",
    f: "🌍",
    k: 260,
    p: 20,
    g: 18,
    l: 12,
    lv: 1,
    i: "Crackers sarrasin 30g, thon 80g, avocat 40g, citron 5ml, sel, poivre",
    st: ["Écraser légèrement l'avocat avec citron.", "Mettre le thon sur les crackers.", "Garnir d'avocat et assaisonner."],
    w: false,
    tags: ["sarrasin", "thon", "avocat", "citron"]
  },
  {
    n: "Barre Avoine Miel Noix Maison",
    f: "🇺🇸",
    k: 252,
    p: 6,
    g: 30,
    l: 12,
    lv: 2,
    i: "Flocons d'avoine 80g, miel 25g, beurre de cacahuète 20g, noix 20g, graines de tournesol 15g",
    st: ["Mélanger tous les ingrédients.", "Étaler dans un moule, presser fermement.", "Réfrigérer 2h, couper en barres."],
    w: false,
    tags: ["avoine", "miel", "cacahuète", "noix", "graines"]
  },
  {
    n: "Tzatziki Concombre Crudités",
    f: "🇬🇷",
    k: 234,
    p: 14,
    g: 22,
    l: 10,
    lv: 1,
    i: "Yaourt grec 150g, concombre 100g, ail 3g, aneth 5g, huile d'olive 8ml, pain pita 40g",
    st: ["Râper le concombre, presser pour extraire l'eau.", "Mélanger avec yaourt, ail et aneth.", "Servir avec pain pita et crudités."],
    w: false,
    tags: ["yaourt", "concombre", "ail", "aneth", "pita"]
  },
  {
    n: "Compote Banane Cacao Beurre Amande",
    f: "🇺🇸",
    k: 232,
    p: 12,
    g: 28,
    l: 8,
    lv: 1,
    i: "Banane 150g, cacao 10g, beurre d'amande 15g, lait écrémé 50ml",
    st: ["Mixer la banane avec le cacao et le lait.", "Ajouter le beurre d'amande.", "Servir en bol ou en verre."],
    w: false,
    tags: ["banane", "cacao", "amande", "lait"]
  },
  {
    n: "Muffin Avoine Myrtilles Maison",
    f: "🇺🇸",
    k: 250,
    p: 8,
    g: 32,
    l: 10,
    lv: 2,
    i: "Farine d'avoine 60g, myrtilles 60g, oeuf 60g, yaourt 60g, miel 15g, levure 3g, huile 8ml",
    st: ["Mélanger farine, oeuf, yaourt et miel.", "Incorporer les myrtilles.", "Cuire en moule à muffin 20 min à 180°C."],
    w: false,
    tags: ["avoine", "myrtilles", "oeuf", "yaourt", "miel"]
  },
  {
    n: "Pudding Chia Coco Mangue",
    f: "🇹🇭",
    k: 244,
    p: 16,
    g: 18,
    l: 12,
    lv: 1,
    i: "Graines de chia 30g, lait de coco 150ml, mangue 80g, yaourt 60g, miel 5g",
    st: ["Mélanger chia avec lait de coco et miel.", "Réfrigérer 4h.", "Servir avec mangue et yaourt."],
    w: false,
    tags: ["chia", "lait de coco", "mangue", "yaourt", "miel"]
  },
  {
    n: "Verrines Fromage Blanc Saumon Aneth",
    f: "🇸🇪",
    k: 288,
    p: 22,
    g: 14,
    l: 16,
    lv: 1,
    i: "Fromage blanc 150g, saumon fumé 80g, aneth 5g, concombre 60g, pain grillé 30g",
    st: ["Couper le saumon et concombre en petits dés.", "Mélanger avec le fromage blanc et l'aneth.", "Servir dans des verrines avec le pain."],
    w: false,
    tags: ["fromage blanc", "saumon", "aneth", "concombre", "pain"]
  },
  {
    n: "Smoothie Mangue Ananas Gingembre",
    f: "🇧🇷",
    k: 240,
    p: 8,
    g: 34,
    l: 8,
    lv: 1,
    i: "Mangue 120g, ananas 100g, yaourt 100g, gingembre 5g, lait de coco 80ml",
    st: ["Mixer tous les ingrédients.", "Ajouter des glaçons.", "Servir frais."],
    w: false,
    tags: ["mangue", "ananas", "yaourt", "gingembre", "lait de coco"]
  },
  {
    n: "Galettes Riz Avocat Tomate",
    f: "🇺🇸",
    k: 252,
    p: 10,
    g: 26,
    l: 12,
    lv: 1,
    i: "Galettes de riz 3x9g, avocat 60g, tomate cerise 60g, citron 5ml, sel, poivre",
    st: ["Tartiner les galettes d'avocat écrasé.", "Garnir de tomates cerises coupées.", "Assaisonner de citron, sel et poivre."],
    w: false,
    tags: ["riz soufflé", "avocat", "tomate", "citron"]
  },
  {
    n: "Labneh Tomates Cerises Zaatar",
    f: "🇱🇧",
    k: 244,
    p: 18,
    g: 16,
    l: 12,
    lv: 1,
    i: "Labneh 120g, tomates cerises 80g, zaatar 5g, huile d'olive 8ml, pain pita 30g",
    st: ["Étaler le labneh dans une assiette.", "Garnir de tomates cerises, zaatar et huile d'olive.", "Servir avec le pain pita."],
    w: false,
    tags: ["labneh", "tomate", "zaatar", "huile", "pita"]
  },
  {
    n: "Shake Whey Fraise Yaourt",
    f: "🥤",
    k: 338,
    p: 32,
    g: 30,
    l: 10,
    lv: 1,
    i: "Whey protéine fraise 35g, fraises 100g, yaourt grec 100g, lait écrémé 150ml",
    st: ["Mixer tous les ingrédients.", "Ajouter des glaçons.", "Servir immédiatement."],
    w: true,
    tags: ["whey", "fraises", "yaourt", "lait"]
  },
  {
    n: "Protein Pancakes Whey Myrtilles",
    f: "🥤",
    k: 356,
    p: 34,
    g: 28,
    l: 12,
    lv: 2,
    i: "Whey protéine 35g, farine d'avoine 50g, oeuf 60g, lait écrémé 80ml, myrtilles 60g",
    st: ["Mélanger whey, farine, oeuf et lait.", "Cuire des pancakes dans une poêle antiadhésive.", "Garnir de myrtilles fraîches."],
    w: true,
    tags: ["whey", "avoine", "oeuf", "lait", "myrtilles"]
  },
  {
    n: "Bowl Protéiné Whey Ananas Coco",
    f: "🥤",
    k: 338,
    p: 30,
    g: 32,
    l: 10,
    lv: 1,
    i: "Whey protéine vanille 30g, lait de coco 150ml, ananas 100g, noix de coco râpée 10g, glaçons 100g",
    st: ["Mixer whey avec lait de coco et ananas.", "Ajouter glaçons.", "Garnir de noix de coco."],
    w: true,
    tags: ["whey", "lait de coco", "ananas", "coco"]
  },
  {
    n: "Shake Whey Café Protéiné",
    f: "🥤",
    k: 322,
    p: 36,
    g: 22,
    l: 10,
    lv: 1,
    i: "Whey protéine café 35g, café expresso froid 60ml, lait écrémé 250ml, glaçons 100g",
    st: ["Préparer un café et laisser refroidir.", "Mixer avec whey et lait.", "Servir avec des glaçons."],
    w: true,
    tags: ["whey", "café", "lait"]
  },
  {
    n: "Mug Cake Whey Vanille Myrtilles",
    f: "🥤",
    k: 328,
    p: 28,
    g: 36,
    l: 8,
    lv: 1,
    i: "Whey protéine vanille 30g, farine d'avoine 40g, oeuf 60g, myrtilles 40g, lait 40ml, levure 2g",
    st: ["Mélanger tous les ingrédients dans un mug.", "Incorporer les myrtilles.", "Cuire 2 min au micro-ondes."],
    w: true,
    tags: ["whey", "avoine", "oeuf", "myrtilles", "lait"]
  },
  {
    n: "Shake Whey Beurre Cacahuète Chocolat",
    f: "🥤",
    k: 348,
    p: 34,
    g: 26,
    l: 12,
    lv: 1,
    i: "Whey protéine chocolat 35g, beurre de cacahuète 20g, lait écrémé 300ml, cacao 5g",
    st: ["Ajouter tous les ingrédients dans le blender.", "Mixer 30 secondes.", "Servir avec des glaçons."],
    w: true,
    tags: ["whey", "cacahuète", "lait", "cacao"]
  },
  {
    n: "Whey Smoothie Bowl Framboise",
    f: "🥤",
    k: 322,
    p: 30,
    g: 28,
    l: 10,
    lv: 1,
    i: "Whey protéine vanille 30g, framboises 120g, banane 80g, lait écrémé 100ml, granola 30g",
    st: ["Mixer whey, framboises, banane et lait.", "Verser dans un bol.", "Garnir de granola."],
    w: true,
    tags: ["whey", "framboises", "banane", "lait", "granola"]
  },
  {
    n: "Protein Ball Whey Cacao Noix",
    f: "🥤",
    k: 314,
    p: 32,
    g: 24,
    l: 10,
    lv: 2,
    i: "Whey protéine chocolat 40g, flocons d'avoine 40g, miel 15g, cacao 10g, noix 15g",
    st: ["Mélanger tous les ingrédients.", "Former des boules compactes.", "Réfrigérer 1h."],
    w: true,
    tags: ["whey", "avoine", "miel", "cacao", "noix"]
  },
  {
    n: "Shake Whey Matcha Lait Amande",
    f: "🥤",
    k: 330,
    p: 30,
    g: 30,
    l: 10,
    lv: 1,
    i: "Whey protéine vanille 30g, matcha 5g, lait d'amande 300ml, miel 10g, glaçons 100g",
    st: ["Mixer tous les ingrédients.", "Verser dans un verre.", "Servir glacé."],
    w: true,
    tags: ["whey", "matcha", "lait d'amande", "miel"]
  },
  {
    n: "Protein Cookie Whey Chocolat",
    f: "🥤",
    k: 332,
    p: 34,
    g: 22,
    l: 12,
    lv: 2,
    i: "Whey protéine chocolat 40g, farine d'avoine 40g, oeuf 60g, beurre de cajou 15g, pépites chocolat 15g",
    st: ["Mélanger tous les ingrédients jusqu'à pâte homogène.", "Former des cookies et disposer sur plaque.", "Cuire 10 min à 180°C."],
    w: true,
    tags: ["whey", "avoine", "oeuf", "cajou", "chocolat"]
  },
  {
    n: "Crackers Avocat Tomate Basilic",
    f: "🇮🇹",
    k: 244,
    p: 8,
    g: 26,
    l: 12,
    lv: 1,
    i: "Crackers complets 40g, avocat 60g, tomate cerise 80g, basilic 5g, huile d'olive 8ml",
    st: ["Écraser l'avocat avec sel et citron.", "Tartiner les crackers.", "Garnir de tomate et basilic."],
    w: false,
    tags: ["crackers", "avocat", "tomate", "basilic", "huile"]
  },
  {
    n: "Soupe Miso Légère Tofu",
    f: "🇯🇵",
    k: 226,
    p: 14,
    g: 20,
    l: 10,
    lv: 1,
    i: "Pâte miso 20g, tofu soyeux 100g, algues wakame 5g, oignons verts 15g, eau chaude 300ml",
    st: ["Dissoudre la pâte miso dans l'eau chaude.", "Ajouter le tofu en dés et les algues.", "Garnir d'oignons verts."],
    w: false,
    tags: ["miso", "tofu", "algues", "oignon vert"]
  },
  {
    n: "Cottage Cheese Ananas Noix Coco",
    f: "🇺🇸",
    k: 254,
    p: 18,
    g: 14,
    l: 14,
    lv: 1,
    i: "Cottage cheese 150g, ananas 80g, noix de coco râpée 20g, miel 5g",
    st: ["Verser le cottage cheese dans un bol.", "Garnir d'ananas, noix de coco et miel."],
    w: false,
    tags: ["cottage cheese", "ananas", "coco", "miel"]
  },
  {
    n: "Bâtonnets Légumes Sauce Tahini",
    f: "🇱🇧",
    k: 236,
    p: 10,
    g: 22,
    l: 12,
    lv: 1,
    i: "Carotte 80g, céleri 60g, concombre 60g, poivron 60g, tahini 25g, citron 10ml",
    st: ["Couper les légumes en bâtonnets.", "Préparer la sauce tahini avec citron et eau.", "Servir ensemble."],
    w: false,
    tags: ["carotte", "céleri", "concombre", "poivron", "tahini"]
  },
  {
    n: "Amandes Grillées Herbes Épicées",
    f: "🌍",
    k: 254,
    p: 12,
    g: 20,
    l: 14,
    lv: 1,
    i: "Amandes 60g, épices mélangées 3g, sel 2g, huile d'olive 5ml, paprika 2g",
    st: ["Mélanger les amandes avec huile et épices.", "Rôtir au four 10 min à 170°C.", "Laisser refroidir avant de servir."],
    w: false,
    tags: ["amandes", "épices", "paprika"]
  },
  {
    n: "Velouté Carotte Gingembre",
    f: "🇫🇷",
    k: 226,
    p: 16,
    g: 18,
    l: 10,
    lv: 1,
    i: "Carotte 200g, gingembre 10g, lait de coco 60ml, bouillon de légumes 200ml, oignon 40g, huile 5ml",
    st: ["Cuire les carottes avec oignon et gingembre.", "Mixer avec le bouillon et le lait de coco.", "Servir chaud ou froid."],
    w: false,
    tags: ["carotte", "gingembre", "lait de coco", "oignon"]
  }
];

var dinner = [
  {
    n: "Saumon Vapeur Épinards",
    f: "🇸🇪",
    k: 480,
    p: 40,
    g: 8,
    l: 32,
    lv: 1,
    i: "Filet de saumon 200g, épinards frais 150g, huile d'olive 15ml, citron 20ml, ail 5g, sel, poivre",
    st: ["Cuire le saumon à la vapeur 12 min.", "Faire sauter les épinards avec ail et huile d'olive.", "Servir avec citron frais."],
    w: false,
    tags: ["saumon", "épinards", "huile", "citron", "ail"]
  },
  {
    n: "Poulet Grillé Légumes Vapeur",
    f: "🌍",
    k: 392,
    p: 48,
    g: 14,
    l: 16,
    lv: 1,
    i: "Blanc de poulet 220g, brocoli 120g, carotte 80g, courgette 80g, huile d'olive 12ml, épices 3g",
    st: ["Mariner le poulet avec épices et huile.", "Griller 6 min de chaque côté.", "Cuire les légumes à la vapeur 8 min. Servir ensemble."],
    w: false,
    tags: ["poulet", "brocoli", "carotte", "courgette", "huile"]
  },
  {
    n: "Cabillaud Courgettes",
    f: "🇸🇪",
    k: 318,
    p: 38,
    g: 10,
    l: 14,
    lv: 1,
    i: "Filet de cabillaud 200g, courgette 150g, huile d'olive 10ml, citron 15ml, herbes de Provence 3g",
    st: ["Assaisonner le cabillaud avec herbes et citron.", "Poêler 4 min de chaque côté.", "Cuire les courgettes en rondelles. Servir."],
    w: false,
    tags: ["cabillaud", "courgette", "huile", "citron"]
  },
  {
    n: "Dinde Haricots Verts",
    f: "🇺🇸",
    k: 376,
    p: 44,
    g: 14,
    l: 16,
    lv: 1,
    i: "Escalope de dinde 200g, haricots verts 200g, ail 5g, huile d'olive 12ml, citron 15ml, thym 2g",
    st: ["Cuire les haricots verts al dente.", "Poêler la dinde avec ail et thym.", "Servir avec citron et huile d'olive."],
    w: false,
    tags: ["dinde", "haricots verts", "ail", "huile", "citron"]
  },
  {
    n: "Omelette Champignons Herbes",
    f: "🇫🇷",
    k: 354,
    p: 24,
    g: 6,
    l: 26,
    lv: 1,
    i: "Oeufs 3x60g, champignons 120g, persil 10g, ciboulette 5g, beurre 15g, sel, poivre",
    st: ["Faire sauter les champignons dans le beurre.", "Battre les oeufs avec les herbes.", "Cuire l'omelette moelleuse, garnir de champignons."],
    w: false,
    tags: ["oeuf", "champignons", "persil", "ciboulette", "beurre"]
  },
  {
    n: "Soupe Miso Saumon",
    f: "🇯🇵",
    k: 374,
    p: 34,
    g: 28,
    l: 14,
    lv: 2,
    i: "Saumon 150g, pâte miso 25g, tofu 100g, algues wakame 10g, oignons verts 20g, nouilles soba 60g",
    st: ["Porter l'eau à ébullition, ajouter les nouilles.", "Cuire le saumon.", "Dissoudre le miso hors feu, ajouter tous les ingrédients."],
    w: false,
    tags: ["saumon", "miso", "tofu", "algues", "nouilles", "oignon vert"]
  },
  {
    n: "Tajine Poulet Citron Confit",
    f: "🇲🇦",
    k: 436,
    p: 46,
    g: 18,
    l: 20,
    lv: 3,
    i: "Cuisses de poulet 220g, citron confit 30g, olives 30g, oignon 60g, ras el hanout 5g, huile d'olive 10ml, coriandre 10g",
    st: ["Faire dorer le poulet avec épices et oignon.", "Ajouter citron confit, olives et 200ml d'eau.", "Mijoter 45 min. Servir avec coriandre."],
    w: false,
    tags: ["poulet", "citron confit", "olives", "oignon", "coriandre"]
  },
  {
    n: "Teriyaki Poulet Brocoli",
    f: "🇯🇵",
    k: 470,
    p: 44,
    g: 42,
    l: 14,
    lv: 2,
    i: "Blanc de poulet 200g, brocoli 150g, sauce teriyaki 30ml, riz 80g, sésame 8g, gingembre 5g",
    st: ["Mariner le poulet dans la sauce teriyaki.", "Griller le poulet, cuire le brocoli vapeur.", "Servir avec riz et sésame."],
    w: false,
    tags: ["poulet", "brocoli", "teriyaki", "riz", "sésame"]
  },
  {
    n: "Crevettes Ail Citron",
    f: "🌍",
    k: 364,
    p: 34,
    g: 12,
    l: 20,
    lv: 1,
    i: "Crevettes 250g, ail 10g, citron 20ml, huile d'olive 15ml, persil 10g, piment 2g",
    st: ["Chauffer l'huile à feu vif.", "Faire sauter les crevettes avec ail et piment 3 min.", "Finir avec citron et persil."],
    w: false,
    tags: ["crevettes", "ail", "citron", "huile", "persil"]
  },
  {
    n: "Pho Boeuf",
    f: "🇻🇳",
    k: 422,
    p: 36,
    g: 38,
    l: 14,
    lv: 3,
    i: "Boeuf 160g, nouilles de riz 100g, bouillon pho 600ml, oignon brûlé 40g, gingembre 15g, basilic 10g, citron vert 15ml, germes de soja 60g",
    st: ["Préparer le bouillon pho avec épices 1h.", "Cuire les nouilles.", "Assembler avec boeuf cru tranché fin (le bouillon le cuit), herbes fraîches."],
    w: false,
    tags: ["boeuf", "nouilles", "gingembre", "basilic", "soja"]
  },
  {
    n: "Blanquette Veau Légère",
    f: "🇫🇷",
    k: 478,
    p: 46,
    g: 24,
    l: 22,
    lv: 4,
    i: "Veau 200g, carotte 80g, champignons 80g, oignon 60g, crème légère 60ml, citron 10ml, bouillon 400ml",
    st: ["Cuire le veau dans le bouillon avec légumes 1h.", "Préparer la sauce à la crème avec citron.", "Filtrer le bouillon, assembler avec la sauce."],
    w: false,
    tags: ["veau", "carotte", "champignons", "oignon", "crème"]
  },
  {
    n: "Tataki Boeuf Sésame",
    f: "🇯🇵",
    k: 396,
    p: 42,
    g: 12,
    l: 20,
    lv: 3,
    i: "Filet de boeuf 200g, sésame 15g, sauce soja 15ml, gingembre 8g, huile de sésame 8ml, salade 60g",
    st: ["Rouler le filet de boeuf dans le sésame.", "Saisir 30 sec de chaque côté à feu très vif.", "Trancher fin, servir sur salade avec sauce soja et gingembre."],
    w: false,
    tags: ["boeuf", "sésame", "soja", "gingembre", "salade"]
  },
  {
    n: "Curry Vert Crevettes",
    f: "🇹🇭",
    k: 442,
    p: 32,
    g: 38,
    l: 18,
    lv: 2,
    i: "Crevettes 200g, lait de coco 100ml, pâte de curry vert 20g, aubergine 100g, riz jasmin 80g, basilic thaï 10g",
    st: ["Faire revenir la pâte de curry dans une poêle.", "Ajouter les crevettes, puis le lait de coco et aubergine.", "Mijoter 10 min. Servir avec riz et basilic."],
    w: false,
    tags: ["crevettes", "lait de coco", "curry vert", "aubergine", "riz", "basilic"]
  },
  {
    n: "Dorade Croûte de Sel",
    f: "🌍",
    k: 390,
    p: 44,
    g: 4,
    l: 22,
    lv: 3,
    i: "Dorade 400g (entière), gros sel 500g, blancs d'oeufs 2x30g, herbes aromatiques 10g, citron 20ml, huile d'olive 10ml",
    st: ["Mélanger le gros sel avec les blancs d'oeufs.", "Envelopper la dorade dans la croûte de sel.", "Cuire 25 min à 200°C. Casser la croûte, servir avec citron."],
    w: false,
    tags: ["dorade", "sel", "herbes", "citron", "huile"]
  },
  {
    n: "Gyoza Dinde Vapeur",
    f: "🇯🇵",
    k: 470,
    p: 38,
    g: 48,
    l: 14,
    lv: 4,
    i: "Dinde hachée 150g, pâtes à gyoza 100g, chou 80g, gingembre 8g, sauce soja 15ml, huile de sésame 8ml, oignons verts 15g",
    st: ["Mélanger dinde, chou, gingembre et assaisonnement.", "Plier les gyoza.", "Cuire à la vapeur 12 min. Servir avec sauce soja et huile de sésame."],
    w: false,
    tags: ["dinde", "chou", "gingembre", "soja", "sésame"]
  },
  {
    n: "Filet de Bar Herbes Vapeur",
    f: "🇫🇷",
    k: 446,
    p: 42,
    g: 20,
    l: 22,
    lv: 2,
    i: "Filet de bar 200g, poireaux 120g, carotte 80g, huile d'olive 15ml, citron 20ml, thym 3g",
    st: ["Cuire les légumes à la vapeur 8 min.", "Cuire le bar vapeur 10 min avec thym.", "Servir avec légumes et citron."],
    w: false,
    tags: ["bar", "poireaux", "carotte", "huile", "citron", "thym"]
  },
  {
    n: "Poulet Moutarde Légumes Rôtis",
    f: "🇫🇷",
    k: 464,
    p: 40,
    g: 22,
    l: 24,
    lv: 2,
    i: "Cuisses de poulet 200g, moutarde 20g, carotte 80g, courgette 80g, oignon 60g, huile d'olive 12ml",
    st: ["Badigeonner le poulet de moutarde.", "Disposer avec les légumes en dés.", "Cuire au four 35 min à 190°C."],
    w: false,
    tags: ["poulet", "moutarde", "carotte", "courgette", "oignon"]
  },
  {
    n: "Thon Grillé Salade Niçoise",
    f: "🇫🇷",
    k: 460,
    p: 38,
    g: 14,
    l: 28,
    lv: 2,
    i: "Thon frais 200g, haricots verts 80g, oeuf dur 60g, tomate 80g, olives 20g, huile d'olive 15ml, moutarde 10g",
    st: ["Griller le thon 2-3 min de chaque côté.", "Cuire les haricots verts al dente.", "Composer la salade, assaisonner à la moutarde."],
    w: false,
    tags: ["thon", "haricots verts", "oeuf", "tomate", "olives", "huile"]
  },
  {
    n: "Salade de Poulet Grillé Roquette",
    f: "🇮🇹",
    k: 438,
    p: 44,
    g: 16,
    l: 22,
    lv: 1,
    i: "Blanc de poulet 200g, roquette 60g, tomates cerises 100g, parmesan 30g, pignons 15g, huile d'olive 12ml, vinaigre balsamique 10ml",
    st: ["Griller le poulet assaisonné.", "Préparer la base de roquette avec tomates et parmesan.", "Trancher le poulet, disposer sur la salade."],
    w: false,
    tags: ["poulet", "roquette", "tomate", "parmesan", "pignons"]
  },
  {
    n: "Steak de Thon Sesame Salade",
    f: "🇯🇵",
    k: 420,
    p: 46,
    g: 14,
    l: 20,
    lv: 2,
    i: "Thon frais 220g, sésame 15g, sauce soja 15ml, huile de sésame 8ml, salade mélangée 80g, gingembre 8g, citron vert 15ml",
    st: ["Paner le thon dans le sésame.", "Saisir 1 min de chaque côté.", "Trancher et servir sur salade avec sauce soja-gingembre."],
    w: false,
    tags: ["thon", "sésame", "soja", "salade", "gingembre"]
  },
  {
    n: "Agneau Grillé Légumes Méditerranéens",
    f: "🇬🇷",
    k: 466,
    p: 40,
    g: 18,
    l: 26,
    lv: 2,
    i: "Côtelettes d'agneau 200g, courgette 80g, poivron 80g, tomate 80g, ail 5g, herbes grecques 5g, huile d'olive 12ml",
    st: ["Mariner les côtelettes avec herbes, ail et huile.", "Griller 4 min de chaque côté.", "Rôtir les légumes séparément."],
    w: false,
    tags: ["agneau", "courgette", "poivron", "tomate", "ail", "huile"]
  },
  {
    n: "Morue Pil Pil Poivrons",
    f: "🇪🇸",
    k: 426,
    p: 38,
    g: 28,
    l: 18,
    lv: 3,
    i: "Morue dessalée 200g, poivrons rôtis 100g, ail 10g, huile d'olive 15ml, pommes de terre 100g",
    st: ["Dessaler la morue 24h.", "Confiture la morue dans l'huile avec ail.", "Laisser émulsionner la sauce, servir avec poivrons et pommes de terre."],
    w: false,
    tags: ["morue", "poivrons", "ail", "huile", "pomme de terre"]
  },
  {
    n: "Boeuf Bourguignon Allégé",
    f: "🇫🇷",
    k: 454,
    p: 42,
    g: 22,
    l: 22,
    lv: 4,
    i: "Boeuf à braiser 200g, carotte 80g, oignon 60g, champignons 80g, bouillon 300ml, concentré de tomate 20g, herbes 5g",
    st: ["Faire dorer le boeuf.", "Ajouter les légumes, le concentré et le bouillon.", "Mijoter 1h30 à feu très doux."],
    w: false,
    tags: ["boeuf", "carotte", "oignon", "champignons", "tomate"]
  },
  {
    n: "Escalope Dinde Légères Vapeur",
    f: "🇺🇸",
    k: 414,
    p: 44,
    g: 10,
    l: 22,
    lv: 1,
    i: "Escalope de dinde 220g, haricots verts 150g, asperges 100g, huile d'olive 12ml, citron 15ml, ail 5g",
    st: ["Cuire dinde à la vapeur ou à la poêle.", "Cuire les légumes al dente.", "Assaisonner avec huile, citron et ail."],
    w: false,
    tags: ["dinde", "haricots verts", "asperges", "huile", "citron"]
  },
  {
    n: "Salade Tiède Boeuf Avocat",
    f: "🇺🇸",
    k: 444,
    p: 36,
    g: 30,
    l: 20,
    lv: 2,
    i: "Boeuf haché maigre 160g, avocat 80g, tomate 80g, maïs 60g, laitue 60g, citron 15ml, épices 3g",
    st: ["Cuire le boeuf haché avec épices.", "Préparer la salade avec tous les légumes.", "Assembler tiède avec le boeuf."],
    w: false,
    tags: ["boeuf", "avocat", "tomate", "maïs", "laitue"]
  },
  {
    n: "Filet de Sole Vapeur Légumes",
    f: "🇫🇷",
    k: 436,
    p: 40,
    g: 24,
    l: 20,
    lv: 1,
    i: "Sole 220g, courgette 100g, carotte 80g, brocoli 80g, huile d'olive 12ml, citron 15ml, estragon 3g",
    st: ["Cuire la sole et les légumes à la vapeur 12 min.", "Arroser d'huile d'olive et citron.", "Garnir d'estragon."],
    w: false,
    tags: ["sole", "courgette", "carotte", "brocoli", "huile", "citron"]
  },
  {
    n: "Poulet Citron Curcuma Épinards",
    f: "🇮🇳",
    k: 442,
    p: 38,
    g: 32,
    l: 18,
    lv: 2,
    i: "Blanc de poulet 180g, épinards 120g, oignon 60g, curcuma 3g, gingembre 8g, citron 15ml, riz 60g, huile 8ml",
    st: ["Poêler le poulet avec curcuma et gingembre.", "Ajouter les épinards.", "Servir avec riz basmati et jus de citron."],
    w: false,
    tags: ["poulet", "épinards", "curcuma", "gingembre", "citron", "riz"]
  },
  {
    n: "Saumon Épinards Crème Légère",
    f: "🇸🇪",
    k: 432,
    p: 42,
    g: 12,
    l: 24,
    lv: 2,
    i: "Saumon 200g, épinards 120g, crème légère 60ml, ail 5g, citron 15ml, aneth 5g, huile 8ml",
    st: ["Poêler le saumon côté peau 4 min.", "Faire une sauce crème avec épinards, ail et citron.", "Servir le saumon nappé de sauce."],
    w: false,
    tags: ["saumon", "épinards", "crème", "ail", "citron", "aneth"]
  },
  {
    n: "Crevettes Curry Coco Légumes",
    f: "🇹🇭",
    k: 436,
    p: 44,
    g: 20,
    l: 20,
    lv: 2,
    i: "Crevettes 220g, lait de coco 80ml, curry rouge 15g, brocoli 100g, poivron 80g, coriandre 10g",
    st: ["Faire revenir le curry dans une poêle.", "Ajouter les crevettes et légumes.", "Incorporer le lait de coco, mijoter 8 min."],
    w: false,
    tags: ["crevettes", "lait de coco", "curry", "brocoli", "poivron", "coriandre"]
  },
  {
    n: "Magret de Canard Légumes Vapeur",
    f: "🇫🇷",
    k: 446,
    p: 40,
    g: 22,
    l: 22,
    lv: 3,
    i: "Magret de canard 180g, haricots verts 120g, carotte 80g, orange 60ml, miel 10g, vinaigre 10ml",
    st: ["Quadriller et cuire le magret côté peau.", "Préparer la sauce orange-miel.", "Servir avec légumes vapeur et sauce."],
    w: false,
    tags: ["canard", "haricots verts", "carotte", "orange", "miel"]
  },
  {
    n: "Cabillaud Tajine Légumes",
    f: "🇲🇦",
    k: 448,
    p: 40,
    g: 18,
    l: 24,
    lv: 2,
    i: "Cabillaud 200g, courgette 80g, tomate 80g, oignon 60g, chermoula 20g, huile d'olive 12ml, coriandre 10g",
    st: ["Mariner le cabillaud dans la chermoula.", "Disposer les légumes dans un tajine.", "Ajouter le poisson, cuire 25 min à couvert."],
    w: false,
    tags: ["cabillaud", "courgette", "tomate", "oignon", "chermoula", "coriandre"]
  },
  {
    n: "Gambas Plancha Sauce Romesco",
    f: "🇪🇸",
    k: 448,
    p: 42,
    g: 16,
    l: 24,
    lv: 2,
    i: "Gambas 220g, poivrons rôtis 100g, amandes 20g, ail 8g, huile d'olive 12ml, piment 3g, citron 15ml",
    st: ["Cuire les gambas à la plancha 2 min de chaque côté.", "Mixer poivrons, amandes, ail pour la sauce romesco.", "Servir avec la sauce."],
    w: false,
    tags: ["gambas", "poivrons", "amandes", "ail", "huile", "citron"]
  },
  {
    n: "Poulet Vapeur Riz Thaï Basilic",
    f: "🇹🇭",
    k: 412,
    p: 44,
    g: 14,
    l: 20,
    lv: 2,
    i: "Blanc de poulet 220g, basilic thaï 15g, ail 8g, piment 3g, sauce de poisson halal 10ml, huile 10ml",
    st: ["Cuire le poulet vapeur ou poêlé.", "Préparer la sauce basilic-ail.", "Servir avec riz thaï jasmin."],
    w: false,
    tags: ["poulet", "basilic", "ail", "piment", "huile"]
  },
  {
    n: "Salade Chaude Poulpe Grillé",
    f: "🇵🇹",
    k: 454,
    p: 40,
    g: 24,
    l: 22,
    lv: 3,
    i: "Poulpe cuit 200g, pomme de terre 100g, tomate 80g, oignon rouge 40g, persil 10g, huile d'olive 12ml, citron 15ml",
    st: ["Griller le poulpe précuit.", "Cuire les pommes de terre.", "Assembler la salade avec tous les ingrédients."],
    w: false,
    tags: ["poulpe", "pomme de terre", "tomate", "oignon", "persil", "huile"]
  },
  {
    n: "Soupe Poulet Légumes Maison",
    f: "🇫🇷",
    k: 454,
    p: 38,
    g: 26,
    l: 22,
    lv: 2,
    i: "Poulet 180g, carotte 80g, navet 60g, poireau 60g, céleri 40g, bouillon 600ml, vermicelles 40g",
    st: ["Cuire le poulet dans le bouillon.", "Ajouter les légumes taillés, cuire 20 min.", "Ajouter vermicelles, cuire 5 min."],
    w: false,
    tags: ["poulet", "carotte", "navet", "poireau", "céleri", "vermicelles"]
  },
  {
    n: "Boeuf Haché Courgette Gratiné",
    f: "🇮🇹",
    k: 446,
    p: 42,
    g: 20,
    l: 22,
    lv: 2,
    i: "Boeuf haché 180g, courgette 200g, tomate 100g, fromage râpé 30g, oignon 60g, herbes 3g",
    st: ["Évider les courgettes et farcir de boeuf haché.", "Napper de sauce tomate.", "Gratiner 25 min à 180°C."],
    w: false,
    tags: ["boeuf", "courgette", "tomate", "fromage", "oignon"]
  },
  {
    n: "Rôti de Dinde Légumes Printaniers",
    f: "🇫🇷",
    k: 454,
    p: 36,
    g: 28,
    l: 22,
    lv: 3,
    i: "Rôti de dinde 200g, asperges 100g, petits pois 80g, carotte 80g, herbes de Provence 3g, huile 12ml",
    st: ["Rôtir la dinde 45 min à 180°C.", "Cuire les légumes vapeur.", "Servir ensemble avec jus de cuisson."],
    w: false,
    tags: ["dinde", "asperges", "petits pois", "carotte", "herbes"]
  },
  {
    n: "Bar en Papillote Légumes",
    f: "🇫🇷",
    k: 448,
    p: 40,
    g: 18,
    l: 24,
    lv: 2,
    i: "Filet de bar 200g, tomate 80g, courgette 80g, olives 20g, herbes de Provence 3g, huile d'olive 12ml, citron 15ml",
    st: ["Placer le bar et légumes sur du papier aluminium.", "Assaisonner avec herbes, olives et citron.", "Fermer la papillote et cuire 20 min à 180°C."],
    w: false,
    tags: ["bar", "tomate", "courgette", "olives", "herbes", "citron"]
  },
  {
    n: "Poulet Sauce Cacahuète Africaine",
    f: "🇸🇳",
    k: 440,
    p: 44,
    g: 12,
    l: 24,
    lv: 3,
    i: "Blanc de poulet 220g, beurre de cacahuète 30g, tomate 100g, oignon 60g, piment 3g, ail 5g, bouillon 200ml",
    st: ["Faire dorer le poulet.", "Préparer la sauce avec cacahuète, tomate et bouillon.", "Mijoter 25 min."],
    w: false,
    tags: ["poulet", "cacahuète", "tomate", "oignon", "piment", "ail"]
  },
  {
    n: "Gratin Dauphinois Poisson",
    f: "🇫🇷",
    k: 446,
    p: 38,
    g: 24,
    l: 22,
    lv: 3,
    i: "Cabillaud 180g, pomme de terre 120g, crème légère 80ml, fromage râpé 30g, ail 5g, noix de muscade 1g",
    st: ["Cuire les pommes de terre à la mandoline.", "Disposer avec le poisson en couches.", "Napper de crème et fromage, gratiner 30 min à 180°C."],
    w: false,
    tags: ["cabillaud", "pomme de terre", "crème", "fromage", "ail"]
  },
  {
    n: "Osso Bucco de Dinde Gremolata",
    f: "🇮🇹",
    k: 438,
    p: 40,
    g: 20,
    l: 22,
    lv: 4,
    i: "Jarret de dinde 220g, tomate 100g, oignon 60g, carotte 60g, gremolata 10g, bouillon 200ml, huile 10ml",
    st: ["Fariner et dorer le jarret.", "Ajouter légumes et bouillon.", "Braiser 1h. Finir avec la gremolata."],
    w: false,
    tags: ["dinde", "tomate", "oignon", "carotte", "gremolata"]
  },
  {
    n: "Mahi Mahi Grillé Salsa Tomate",
    f: "🇧🇷",
    k: 440,
    p: 42,
    g: 14,
    l: 24,
    lv: 2,
    i: "Filet de mahi mahi 220g, tomate 100g, oignon rouge 40g, coriandre 10g, piment 3g, huile d'olive 12ml, citron vert 20ml",
    st: ["Griller le mahi mahi assaisonné 4 min de chaque côté.", "Préparer la salsa tomate fraîche.", "Servir avec la salsa."],
    w: false,
    tags: ["mahi mahi", "tomate", "oignon", "coriandre", "piment", "citron"]
  },
  {
    n: "Grillades Poulet Citron Origan",
    f: "🇬🇷",
    k: 438,
    p: 44,
    g: 16,
    l: 22,
    lv: 2,
    i: "Blanc de poulet 220g, citron 30ml, origan 5g, ail 8g, huile d'olive 12ml, courgette grillée 100g",
    st: ["Mariner le poulet dans citron, ail et origan.", "Griller 6 min de chaque côté.", "Servir avec courgette grillée."],
    w: false,
    tags: ["poulet", "citron", "origan", "ail", "huile", "courgette"]
  },
  {
    n: "Lotte Sauce Curry Légume Vapeur",
    f: "🇫🇷",
    k: 444,
    p: 38,
    g: 28,
    l: 20,
    lv: 3,
    i: "Lotte 200g, lait de coco 80ml, curry 8g, brocoli 100g, carotte 80g, oignon 40g",
    st: ["Poêler la lotte.", "Préparer la sauce curry au lait de coco.", "Cuire les légumes vapeur. Servir ensemble."],
    w: false,
    tags: ["lotte", "lait de coco", "curry", "brocoli", "carotte"]
  },
  {
    n: "Poulet au Four Légumes Méditerranéens",
    f: "🇪🇸",
    k: 436,
    p: 40,
    g: 24,
    l: 20,
    lv: 2,
    i: "Poulet 200g, aubergine 100g, poivron 80g, tomate 80g, ail 8g, herbes 3g, huile d'olive 12ml",
    st: ["Disposer poulet et légumes dans un plat.", "Assaisonner d'herbes, ail et huile.", "Cuire 40 min à 190°C."],
    w: false,
    tags: ["poulet", "aubergine", "poivron", "tomate", "ail", "herbes"]
  },
  {
    n: "Lieu Noir Épinards Ail",
    f: "🇫🇷",
    k: 438,
    p: 42,
    g: 18,
    l: 22,
    lv: 1,
    i: "Lieu noir 220g, épinards 150g, ail 8g, huile d'olive 12ml, citron 15ml, pomme de terre 80g",
    st: ["Cuire les pommes de terre.", "Poêler le lieu noir assaisonné.", "Faire revenir épinards et ail. Servir ensemble."],
    w: false,
    tags: ["lieu noir", "épinards", "ail", "huile", "pomme de terre"]
  },
  {
    n: "Boulettes Dinde Sauce Tomate",
    f: "🇮🇹",
    k: 430,
    p: 44,
    g: 14,
    l: 22,
    lv: 2,
    i: "Dinde hachée 220g, tomates 150g, oignon 60g, ail 5g, basilic 10g, parmesan 20g, huile 10ml",
    st: ["Former les boulettes de dinde avec épices.", "Cuire dans la sauce tomate 20 min.", "Garnir de parmesan et basilic."],
    w: false,
    tags: ["dinde", "tomate", "oignon", "ail", "basilic", "parmesan"]
  },
  {
    n: "Soupe Tom Yum Crevettes",
    f: "🇹🇭",
    k: 438,
    p: 40,
    g: 20,
    l: 22,
    lv: 2,
    i: "Crevettes 200g, champignons 100g, citronnelle 10g, galanga 8g, citron vert 20ml, piment 3g, tomate cerise 60g, lait de coco 60ml",
    st: ["Préparer le bouillon avec citronnelle, galanga et piment.", "Ajouter crevettes et champignons.", "Finir avec citron vert et lait de coco."],
    w: false,
    tags: ["crevettes", "champignons", "citronnelle", "galanga", "citron", "piment"]
  },
  {
    n: "Roulades Poulet Épinards Fromage",
    f: "🇫🇷",
    k: 454,
    p: 42,
    g: 22,
    l: 22,
    lv: 3,
    i: "Blanc de poulet 200g, épinards cuits 80g, fromage de chèvre 40g, tomate 80g, huile 10ml, ail 5g",
    st: ["Aplatir les blancs de poulet.", "Farcir d'épinards et fromage de chèvre.", "Rouler, ficeler et cuire 25 min au four à 180°C."],
    w: false,
    tags: ["poulet", "épinards", "chèvre", "tomate", "ail"]
  },
  {
    n: "Filet de Boeuf Sauce Champignons",
    f: "🇫🇷",
    k: 444,
    p: 40,
    g: 26,
    l: 20,
    lv: 3,
    i: "Filet de boeuf 180g, champignons 120g, crème légère 60ml, oignon 40g, bouillon 100ml, persil 5g, huile 10ml",
    st: ["Saisir le filet de boeuf à feu très vif.", "Préparer la sauce champignons à la crème.", "Servir avec la sauce et persil."],
    w: false,
    tags: ["boeuf", "champignons", "crème", "oignon", "persil"]
  }
];

window.breakfast = breakfast;
window.lunch = lunch;
window.snack = snack;
window.dinner = dinner;
